// Copyright (c) 2026 Darknode-Official (Manav Prasad). All rights reserved. See LICENSE.
// Curated how-to answers: the everyday developer questions that have one well-known,
// correct answer ("git undo last commit", "center a div", "python list comprehension").
// Every entry is hand-written and carries the exact command or snippet; a question that
// matches no entry is not claimed (ask() returns null), so DI never improvises a how-to.

const H = [];
const add = (id, re, title, lang, code, body, note) => H.push({ id, re, title, lang, code, body: body || "", note: note || "" });

// ---------------------------------------------------------------------------
// install
add("install-python", /\binstall(?:ing)? python\b|\bpython install(?:ation)?\b|\bget python\b/i, "Install Python", "bash",
  "# Windows: download from https://www.python.org/downloads/ (tick \"Add python.exe to PATH\"), or\nwinget install Python.Python.3.13\n\n# macOS (Homebrew)\nbrew install python\n\n# Ubuntu / Debian\nsudo apt update && sudo apt install python3 python3-pip python3-venv\n\n# check it worked\npython3 --version",
  "On Windows the command is usually `python` or `py` rather than `python3`.");
add("install-node", /\binstall(?:ing)? (?:node(?:\.?js)?|npm)\b/i, "Install Node.js", "bash",
  "# any OS: the LTS installer from https://nodejs.org, or a version manager:\ncurl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash\nnvm install --lts\n\n# macOS (Homebrew)\nbrew install node\n\n# Windows\nwinget install OpenJS.NodeJS.LTS\n\n# check\nnode --version && npm --version", "");
add("install-git", /\binstall(?:ing)? git\b/i, "Install Git", "bash",
  "# Windows\nwinget install Git.Git\n\n# macOS (also comes with the Xcode command line tools)\nbrew install git\n\n# Ubuntu / Debian\nsudo apt install git\n\n# first-time setup\ngit config --global user.name \"Your Name\"\ngit config --global user.email \"you@example.com\"", "");
// git
// ---------------------------------------------------------------------------
add("git-undo-commit", /\bgit\b.*\b(?:undo|revert|remove|cancel|uncommit|take back)\b.*\b(?:last|latest|previous|recent|my|a|the|that)\b.*\bcommit|\b(?:undo|uncommit|revert) (?:a |the |my |that )?(?:git )?commit\b|\b(?:undo|uncommit|take back)\b.*\blast (?:git )?commit|\bgit (?:reset|undo) (?:the )?last commit/i, "Undo the last git commit", "bash",
  "# keep the changes staged (soft)\ngit reset --soft HEAD~1\n\n# keep the changes in the working tree, unstaged (default, mixed)\ngit reset HEAD~1\n\n# throw the commit AND its changes away (hard, destructive)\ngit reset --hard HEAD~1\n\n# already pushed? make a new commit that reverses it instead\ngit revert HEAD",
  "`reset` rewrites local history; use `revert` for anything already pushed to a shared branch.");
add("git-amend", /\bgit\b.*\b(?:amend|edit|change|fix|reword)\b.*\b(?:last |latest |previous )?commit(?: message)?|\bchange (?:the )?(?:last )?commit message/i, "Amend the last commit", "bash",
  "# change only the message\ngit commit --amend -m \"new message\"\n\n# add forgotten files to it, keep the message\ngit add forgotten.txt\ngit commit --amend --no-edit",
  "Amending replaces the commit; if it was already pushed you will need `git push --force-with-lease`.");
add("git-unstage", /\bgit\b.*\b(?:unstage|un-stage|remove from (?:the )?(?:staging|index)|undo (?:git )?add)\b|\bundo git add\b/i, "Unstage a file", "bash", "git restore --staged path/to/file\n# or, older git\ngit reset HEAD path/to/file", "The change stays in your working tree; only the index entry is undone.");
add("git-discard", /\bgit\b.*\b(?:discard|throw away|drop|undo|revert)\b.*\b(?:local |uncommitted |working |unstaged )?changes\b|\bgit checkout -- \./i, "Discard local changes", "bash",
  "# one file\ngit restore path/to/file\n\n# everything tracked (destructive)\ngit restore .\n\n# also delete untracked files and directories (destructive)\ngit clean -fd",
  "There is no undo for `restore`/`clean` on uncommitted work; `git stash` first if unsure.");
add("git-stash", /\bgit stash\b|\bhow (?:do i|to) stash\b|\bstash (?:my )?changes\b/i, "Stash changes", "bash", "git stash                 # save tracked changes\ngit stash -u              # include untracked files\ngit stash list\ngit stash pop             # reapply the latest and drop it\ngit stash apply stash@{1} # reapply a specific one, keep it", "");
add("git-new-branch", /\bgit\b.*\b(?:create|make|new|start)\b.*\bbranch\b|\bcreate (?:a )?(?:new )?branch\b/i, "Create and switch to a new branch", "bash", "git switch -c feature/name\n# older git\ngit checkout -b feature/name\n\n# push it and set upstream\ngit push -u origin feature/name", "");
add("git-delete-branch", /\bgit\b.*\b(?:delete|remove)\b.*\bbranch\b|\bdelete (?:a |the )?(?:git |remote |local )?branch\b/i, "Delete a branch", "bash", "# local (only if merged)\ngit branch -d name\n# local, force\ngit branch -D name\n# remote\ngit push origin --delete name", "");
add("git-rename-branch", /\bgit\b.*\brename\b.*\bbranch\b|\brename (?:a |the |my )?(?:git |current )?branch\b/i, "Rename a branch", "bash", "git branch -m old-name new-name   # or `git branch -m new-name` for the current one\ngit push origin -u new-name\ngit push origin --delete old-name", "");
add("git-squash", /\bgit\b.*\bsquash\b|\bsquash (?:my |the |several |multiple )?commits\b/i, "Squash the last N commits", "bash", "# interactive: mark all but the first as `squash` (or `s`)\ngit rebase -i HEAD~3\n\n# non-interactive: collapse the last 3 into one new commit\ngit reset --soft HEAD~3\ngit commit -m \"one message\"", "");
add("git-cherry-pick", /\bgit\b.*\bcherry[- ]?pick\b|\bcherry[- ]?pick (?:a )?commit\b/i, "Cherry-pick a commit", "bash", "git cherry-pick <sha>\n# several\ngit cherry-pick <sha1> <sha2>\n# resolve conflicts, then\ngit cherry-pick --continue", "");
add("git-log", /\bgit\b.*\b(?:log|history)\b.*\b(?:one line|oneline|graph|pretty|compact)\b|\bgit (?:log|history) (?:as |in )?(?:a )?(?:one line|graph|tree)|\bshow (?:git )?(?:commit )?history\b/i, "Pretty git log", "bash", "git log --oneline --graph --decorate --all\n# last 10 with author and date\ngit log -10 --pretty=format:'%h %an %ad %s' --date=short", "");
add("git-diff-staged", /\bgit\b.*\bdiff\b.*\b(?:staged|cached|index)\b|\bsee (?:what is |what's )?staged\b/i, "Diff what is staged", "bash", "git diff --staged   # (alias: --cached)\ngit diff            # unstaged only\ngit diff HEAD       # both", "");
add("git-remote-url", /\bgit\b.*\b(?:change|set|update|show|get|see|check)\b.*\bremote\b(?: url| origin)?|\bgit remote (?:url|origin)\b/i, "Show or change the remote URL", "bash", "git remote -v\ngit remote set-url origin git@github.com:user/repo.git\ngit remote add upstream https://github.com/other/repo.git", "");
add("git-force-push", /\bgit\b.*\bforce[- ]push\b|\bpush --force|\bforce push\b/i, "Force push safely", "bash", "git push --force-with-lease origin branch-name", "`--force-with-lease` refuses if someone else pushed in the meantime; plain `--force` overwrites their work.");
add("git-ignore-tracked", /\bgit\b.*\b(?:stop tracking|untrack|ignore)\b.*\b(?:tracked|already|file)\b|\b\.gitignore (?:not working|ignored file still)|\bremove (?:a )?file from git (?:but|without)/i, "Stop tracking a file that is already committed", "bash", "echo \"secrets.env\" >> .gitignore\ngit rm --cached secrets.env\ngit commit -m \"stop tracking secrets.env\"", "`--cached` removes it from the index only; the file stays on disk. It remains in old commits.");
add("git-tag", /\bgit\b.*\b(?:tag|release)\b.*\b(?:create|make|push|add)\b|\b(?:create|make|push) (?:a )?(?:git )?tag\b/i, "Create and push a tag", "bash", "git tag -a v1.2.0 -m \"v1.2.0\"\ngit push origin v1.2.0\n# all tags\ngit push --tags", "");
add("git-merge-vs-rebase", /\b(?:merge|merging)\b.*\b(?:vs|versus|or|compared to)\b.*\brebase|\brebase\b.*\b(?:vs|versus|or)\b.*\bmerge|\bdifference between (?:git )?merge and rebase/i, "Merge vs rebase", "bash", "# merge: keeps both histories, adds a merge commit\ngit switch feature && git merge main\n\n# rebase: replays your commits on top of main, linear history\ngit switch feature && git rebase main", "Rebase rewrites the feature branch's commits, so do it only on branches nobody else has pulled.");
add("git-resolve-conflict", /\b(?:resolve|fix)\b.*\b(?:merge )?conflicts?\b|\bmerge conflict\b/i, "Resolve a merge conflict", "bash", "git status                      # lists the conflicted files\n# edit each file: keep what you want between <<<<<<< ======= >>>>>>>\ngit add path/to/file\ngit commit                      # for a merge\ngit rebase --continue           # for a rebase\n# give up\ngit merge --abort   # or: git rebase --abort", "");
add("git-clone-branch", /\bgit clone\b.*\b(?:branch|specific|single)\b|\bclone (?:a |one )?(?:specific |single |particular )?branch\b/i, "Clone one branch", "bash", "git clone --branch name --single-branch https://github.com/user/repo.git", "");
add("git-shallow", /\bshallow clone\b|\bgit clone\b.*\bdepth\b|\bclone (?:only |just )?(?:the )?(?:latest|last) commit/i, "Shallow clone", "bash", "git clone --depth 1 https://github.com/user/repo.git", "");

// ---------------------------------------------------------------------------
// CSS / HTML
// ---------------------------------------------------------------------------
add("css-center-div", /\b(?:center|centre|centering|centred|centered)\b.*\b(?:a |the |my )?(?:div|element|box|content|item)\b|\bcenter (?:something )?(?:horizontally|vertically)|\bvertically (?:and horizontally )?(?:center|centre|align)/i, "Center a div", "css",
  "/* parent */\n.parent {\n  display: grid;\n  place-items: center;   /* horizontal + vertical */\n}\n\n/* or flexbox */\n.parent {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n\n/* a fixed-width block, horizontally only */\n.child { width: 300px; margin-inline: auto; }",
  "The parent needs a height for vertical centering to be visible (e.g. `min-height: 100vh`).");
add("css-truncate", /\b(?:truncate|ellipsis|clip|cut off)\b.*\btext\b|\btext[- ]overflow\b|\bshow (?:an )?ellipsis\b/i, "Truncate text with an ellipsis", "css", "/* one line */\n.one { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n\n/* N lines */\n.lines { display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }", "");
add("css-sticky-footer", /\bsticky footer\b|\bfooter\b.*\b(?:bottom|stick|stay)\b.*\b(?:page|bottom)\b|\bkeep (?:the )?footer at the bottom/i, "Sticky footer", "css", "body { min-height: 100dvh; display: flex; flex-direction: column; margin: 0; }\nmain { flex: 1; }\n/* footer needs nothing special */", "");
add("css-aspect-ratio", /\baspect[- ]ratio\b.*\b(?:css|box|video|image|div)|\b(?:16:9|16 by 9|square) (?:box|div|container)\b|\bresponsive (?:video|iframe) (?:embed|container)/i, "Keep an aspect ratio", "css", ".box { aspect-ratio: 16 / 9; width: 100%; }\n.box > iframe, .box > video { width: 100%; height: 100%; }", "");
add("css-grid-responsive", /\bresponsive (?:css )?grid\b|\bgrid\b.*\b(?:auto[- ]fit|auto[- ]fill|responsive columns)\b|\bcss grid (?:with )?(?:auto|responsive|fluid) columns/i, "Responsive grid without media queries", "css", ".grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));\n  gap: 16px;\n}", "");
add("css-dark-mode", /\bdark mode\b.*\b(?:css|media query|detect|prefers)\b|\bprefers[- ]color[- ]scheme\b|\bcss (?:for )?dark mode\b|\bdetect dark mode/i, "Dark mode in CSS", "css", ":root { --bg: #fff; --fg: #111; }\n@media (prefers-color-scheme: dark) {\n  :root { --bg: #111; --fg: #eee; color-scheme: dark; }\n}\nbody { background: var(--bg); color: var(--fg); }", "");
add("css-hide-scrollbar", /\bhide (?:the )?scrollbar\b|\bremove (?:the )?scrollbar\b|\bscrollbar\b.*\b(?:hide|invisible|none)\b/i, "Hide the scrollbar but keep scrolling", "css", ".scroll { overflow: auto; scrollbar-width: none; }        /* Firefox */\n.scroll::-webkit-scrollbar { display: none; }            /* Chrome, Safari, Edge */", "");
add("css-smooth-scroll", /\bsmooth scroll(?:ing)?\b/i, "Smooth scrolling", "css", "html { scroll-behavior: smooth; }\n/* or from JS */\nel.scrollIntoView({ behavior: \"smooth\", block: \"start\" });", "");
add("css-transition", /\bcss (?:hover )?transition\b|\banimate (?:on )?hover\b|\bfade (?:in|out) (?:with |in )?css\b|\bcss fade\b/i, "CSS transition on hover", "css", ".btn { background: #2563eb; transition: background 150ms ease, transform 150ms ease; }\n.btn:hover { background: #1d4ed8; transform: translateY(-1px); }\n\n/* fade in */\n@keyframes fade { from { opacity: 0 } to { opacity: 1 } }\n.card { animation: fade 300ms ease both; }", "");
add("css-reset-button", /\b(?:reset|remove|strip|unstyle)\b.*\b(?:default )?button (?:styles?|styling|css)\b|\bbutton\b.*\blook like (?:a )?(?:link|text)\b/i, "Reset a button's default styles", "css", "button.plain { all: unset; cursor: pointer; font: inherit; color: inherit; }\nbutton.plain:focus-visible { outline: 2px solid currentColor; outline-offset: 2px; }", "");
add("css-variables", /\bcss (?:custom properties|variables?)\b.*\b(?:how|use|define|declare)\b|\b(?:how (?:do i|to) )?(?:use|define|declare) (?:a )?css (?:variable|custom property)/i, "CSS custom properties", "css", ":root { --accent: #2563eb; --gap: 12px; }\n.card { border: 1px solid var(--accent); padding: var(--gap, 8px); } /* 8px is the fallback */\n/* override in a scope */\n.dark { --accent: #93c5fd; }", "");
add("css-font-import", /\b(?:import|load|add|use)\b.*\b(?:google )?fonts?\b.*\b(?:css|html|website|page)\b|\bgoogle fonts? (?:in|into) (?:css|html)/i, "Load a Google Font", "html", "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap\" rel=\"stylesheet\">\n<style>body { font-family: Inter, system-ui, sans-serif; }</style>", "");
add("html-viewport", /\bviewport meta\b|\bmeta viewport\b|\bmake (?:my |the )?(?:page|site|html) (?:responsive|mobile[- ]friendly)\b/i, "Viewport meta tag", "html", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">", "Without it, phones render the page at ~980px wide and zoom out.");

// ---------------------------------------------------------------------------
// JavaScript
// ---------------------------------------------------------------------------
add("js-fetch-json", /\b(?:fetch|get|load|request)\b.*\bjson\b.*\b(?:js|javascript|fetch|api)\b|\bfetch api example\b|\bjavascript fetch\b|\bhow (?:do i|to) (?:use )?fetch\b/i, "Fetch JSON", "javascript", "const res = await fetch(\"/api/items\", { headers: { Accept: \"application/json\" } });\nif (!res.ok) throw new Error(\"HTTP \" + res.status);\nconst data = await res.json();\n\n// POST\nawait fetch(\"/api/items\", {\n  method: \"POST\",\n  headers: { \"Content-Type\": \"application/json\" },\n  body: JSON.stringify({ name: \"x\" }),\n});", "");
add("js-debounce", /\bdebounce\b.*\b(?:js|javascript|function|input)\b|\b(?:js|javascript) debounce\b|\bhow (?:do i|to) debounce\b/i, "Debounce a function", "javascript", "function debounce(fn, ms = 300) {\n  let t;\n  return (...args) => { clearTimeout(t); t = setTimeout(() => fn(...args), ms); };\n}\ninput.addEventListener(\"input\", debounce((e) => search(e.target.value), 250));", "");
add("js-throttle", /\bthrottle\b.*\b(?:js|javascript|function|scroll)\b|\b(?:js|javascript) throttle\b/i, "Throttle a function", "javascript", "function throttle(fn, ms = 100) {\n  let last = 0;\n  return (...args) => { const now = Date.now(); if (now - last >= ms) { last = now; fn(...args); } };\n}", "");
add("js-copy-clipboard", /\bcopy\b.*\b(?:to (?:the )?clipboard|clipboard)\b.*\b(?:js|javascript|browser)?|\bclipboard\b.*\b(?:js|javascript)\b|\bcopy text (?:to clipboard )?(?:in|with) (?:js|javascript)/i, "Copy to the clipboard", "javascript", "button.addEventListener(\"click\", async () => {\n  try { await navigator.clipboard.writeText(text); }\n  catch { /* fallback: select the text so the user can Ctrl+C */ }\n});", "Must run inside a user gesture (click) on a secure (https) page.");
add("js-deep-clone", /\bdeep (?:clone|copy)\b.*\b(?:js|javascript|object)?|\bclone (?:an )?object (?:in )?(?:js|javascript)\b|\bcopy (?:an )?object without reference/i, "Deep clone an object", "javascript", "const copy = structuredClone(obj);           // modern browsers + Node 17+\n// shallow only:\nconst shallow = { ...obj };\n// JSON round-trip (drops functions, Dates become strings):\nconst j = JSON.parse(JSON.stringify(obj));", "");
add("js-unique-array", /\b(?:unique|dedupe|deduplicate|distinct|remove duplicates)\b.*\barray\b.*\b(?:js|javascript)?|\b(?:js|javascript)\b.*\b(?:unique|dedupe)\b.*\barray|\bremove duplicates from (?:an )?array/i, "Unique values in an array", "javascript", "const unique = [...new Set(arr)];\n// by a key\nconst byId = [...new Map(items.map((x) => [x.id, x])).values()];", "");
add("js-sort-objects", /\bsort\b.*\barray of objects\b|\bsort objects by (?:a )?(?:key|property|field)\b|\bsort by (?:key|property|field) (?:in )?(?:js|javascript)/i, "Sort an array of objects", "javascript", "items.sort((a, b) => a.price - b.price);                 // numeric asc\nitems.sort((a, b) => a.name.localeCompare(b.name));       // string\nitems.sort((a, b) => b.date - a.date);                    // Date desc", "`sort` mutates; use `items.toSorted(...)` or `[...items].sort(...)` to keep the original.");
add("js-group-by", /\bgroup ?by\b.*\b(?:js|javascript|array)\b|\bgroup (?:an )?array (?:of objects )?by\b/i, "Group an array by a key", "javascript", "const groups = Object.groupBy(items, (x) => x.category);   // ES2024\n// older\nconst g = items.reduce((acc, x) => ((acc[x.category] ??= []).push(x), acc), {});", "");
add("js-sleep", /\b(?:sleep|wait|delay|pause)\b.*\b(?:js|javascript|async|promise)\b|\b(?:js|javascript) (?:sleep|wait|delay)\b|\bsettimeout (?:as |with )?(?:a )?promise/i, "Sleep / wait in JavaScript", "javascript", "const sleep = (ms) => new Promise((r) => setTimeout(r, ms));\nawait sleep(1000);", "");
add("js-query-params", /\b(?:get|read|parse)\b.*\b(?:query|url) (?:params?|parameters?|string)\b.*\b(?:js|javascript)?|\burlsearchparams\b|\bquery string (?:in |with )?(?:js|javascript)/i, "Read URL query parameters", "javascript", "const params = new URLSearchParams(location.search);\nconst page = params.get(\"page\");        // null if absent\nconst all = Object.fromEntries(params);  // { page: \"2\", q: \"x\" }", "");
add("js-format-date", /\bformat (?:a )?date\b.*\b(?:js|javascript)?|\b(?:js|javascript) (?:date )?format(?:ting)?\b|\bdate to (?:yyyy-mm-dd|iso) (?:in )?(?:js|javascript)/i, "Format a date", "javascript", "const d = new Date();\nd.toISOString().slice(0, 10);                                   // 2026-09-29\nd.toLocaleDateString(\"en-GB\", { day: \"2-digit\", month: \"short\", year: \"numeric\" }); // 29 Sept 2026\nnew Intl.DateTimeFormat(\"en-US\", { dateStyle: \"medium\", timeStyle: \"short\" }).format(d);", "");
add("js-random-int", /\brandom (?:integer|int|number)\b.*\b(?:js|javascript)\b|\b(?:js|javascript) random (?:integer|int|number)\b|\bmath\.random (?:between|range|integer)/i, "Random integer in a range", "javascript", "const randInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;\n// cryptographically strong\nconst [n] = crypto.getRandomValues(new Uint32Array(1)); // 0 .. 2^32-1", "");
add("js-event-delegation", /\bevent delegation\b|\blisten (?:for )?clicks? on (?:dynamic|dynamically added|future) elements\b/i, "Event delegation", "javascript", "list.addEventListener(\"click\", (e) => {\n  const btn = e.target.closest(\"button[data-id]\");\n  if (!btn || !list.contains(btn)) return;\n  remove(btn.dataset.id);\n});", "");
add("js-local-storage", /\b(?:use|save to|store in|read from)\b.*\blocalstorage\b|\blocalstorage (?:example|json|object)\b|\bsave (?:an )?object (?:to|in) localstorage/i, "Store JSON in localStorage", "javascript", "localStorage.setItem(\"prefs\", JSON.stringify(prefs));\nconst prefs = JSON.parse(localStorage.getItem(\"prefs\") || \"{}\");\nlocalStorage.removeItem(\"prefs\");", "Wrap in try/catch: private windows and blocked storage can throw.");
add("js-check-empty-object", /\bcheck (?:if|whether) (?:an )?object is empty\b|\bempty object (?:check|test)\b/i, "Check for an empty object", "javascript", "const isEmpty = (o) => o != null && Object.keys(o).length === 0;", "");
add("js-optional-chaining", /\boptional chaining\b|\bnullish coalescing\b|\bwhat (?:is|does) \?\.|\b\?\? (?:operator|in js)\b/i, "Optional chaining and nullish coalescing", "javascript", "const city = user?.address?.city;      // undefined instead of a TypeError\nconst name = input ?? \"anonymous\";      // only null/undefined fall through (0 and \"\" do not)\nuser?.save?.();                          // call only if it exists", "");
add("js-promise-all", /\bpromise\.all\b|\brun (?:promises|async (?:functions|calls)) in parallel\b|\bawait (?:multiple|several) (?:promises|fetches)\b/i, "Run promises in parallel", "javascript", "const [a, b] = await Promise.all([fetchA(), fetchB()]);       // rejects on the first failure\nconst results = await Promise.allSettled([fetchA(), fetchB()]); // never rejects; check .status", "");
add("node-read-file", /\b(?:read|write) (?:a )?file\b.*\bnode(?:\.?js)?\b|\bnode(?:\.?js)? (?:read|write) (?:a )?file\b|\bfs\.readfile\b/i, "Read and write a file in Node", "javascript", "import { readFile, writeFile } from \"node:fs/promises\";\nconst text = await readFile(\"in.txt\", \"utf8\");\nawait writeFile(\"out.txt\", text.toUpperCase());\n\n// sync\nimport fs from \"node:fs\";\nconst t = fs.readFileSync(\"in.txt\", \"utf8\");", "");
add("node-env", /\b(?:read|use|load)\b.*\b(?:environment variables?|env vars?|\.env)\b.*\bnode|\bprocess\.env\b|\bdotenv\b/i, "Environment variables in Node", "javascript", "const port = process.env.PORT ?? 3000;\n\n// load a .env file (Node 20.6+; no package needed)\n//   node --env-file=.env server.js", "");

// ---------------------------------------------------------------------------
// Python
// ---------------------------------------------------------------------------
add("py-list-comprehension", /\blist comprehension\b|\bpython\b.*\bcomprehension\b/i, "Python list comprehension", "python", "squares = [x * x for x in range(10)]\nevens = [x for x in nums if x % 2 == 0]\npairs = [(a, b) for a in xs for b in ys]\n\n# dict and set comprehensions\nlengths = {w: len(w) for w in words}\nuniq = {w.lower() for w in words}\n\n# generator (lazy)\ntotal = sum(x * x for x in range(10))", "");
add("py-read-file", /\bpython\b.*\b(?:read|open|write|append)\b.*\bfile\b|\b(?:read|write) (?:a )?(?:text )?file (?:in|with) python\b/i, "Read and write a file in Python", "python", "with open(\"in.txt\", encoding=\"utf-8\") as f:\n    text = f.read()          # or f.readlines(), or iterate: for line in f\n\nwith open(\"out.txt\", \"w\", encoding=\"utf-8\") as f:\n    f.write(text)\n\n# pathlib one-liners\nfrom pathlib import Path\ntext = Path(\"in.txt\").read_text(encoding=\"utf-8\")\nPath(\"out.txt\").write_text(text, encoding=\"utf-8\")", "");
add("py-json", /\bpython\b.*\b(?:json)\b.*\b(?:read|load|parse|write|dump|file)\b|\b(?:parse|read|load|write) json (?:in|with) python\b/i, "JSON in Python", "python", "import json\ndata = json.loads('{\"a\": 1}')                      # string -> object\ntext = json.dumps(data, indent=2, ensure_ascii=False)\n\nwith open(\"data.json\") as f:\n    data = json.load(f)\nwith open(\"out.json\", \"w\") as f:\n    json.dump(data, f, indent=2)", "");
add("py-venv", /\b(?:virtual ?env|venv|virtual environment)\b.*\bpython\b|\bpython\b.*\b(?:virtual ?env|venv|virtual environment)\b|\bcreate (?:a )?venv\b/i, "Python virtual environment", "bash", "python3 -m venv .venv\nsource .venv/bin/activate      # Windows: .venv\\Scripts\\activate\npip install -r requirements.txt\npip freeze > requirements.txt\ndeactivate", "");
add("py-main-guard", /\bif __name__ ?== ?['\"]__main__['\"]|\b__name__\b.*\b__main__\b|\bpython main guard\b/i, "The __main__ guard", "python", "def main():\n    ...\n\nif __name__ == \"__main__\":\n    main()", "The block runs when the file is executed directly, not when it is imported.");
add("py-argparse", /\bargparse\b|\bpython\b.*\b(?:command[- ]line|cli) (?:args?|arguments|flags|options)\b|\bparse (?:command[- ]line )?arguments (?:in )?python/i, "Command-line arguments in Python", "python", "import argparse\np = argparse.ArgumentParser(description=\"Tool\")\np.add_argument(\"path\")\np.add_argument(\"-n\", \"--count\", type=int, default=1)\np.add_argument(\"-v\", \"--verbose\", action=\"store_true\")\nargs = p.parse_args()\nprint(args.path, args.count, args.verbose)", "");
add("py-dict-sort", /\bsort (?:a )?dict(?:ionary)?\b.*\bpython\b|\bpython\b.*\bsort (?:a )?dict(?:ionary)?(?: by value| by key)?\b/i, "Sort a dictionary", "python", "by_key = dict(sorted(d.items()))\nby_val = dict(sorted(d.items(), key=lambda kv: kv[1], reverse=True))", "");
add("py-enumerate-zip", /\benumerate\b.*\bpython\b|\bpython\b.*\b(?:enumerate|zip)\b|\bloop with index (?:in )?python\b/i, "enumerate and zip", "python", "for i, item in enumerate(items, start=1):\n    print(i, item)\n\nfor name, score in zip(names, scores):\n    print(name, score)", "");
add("py-fstring", /\bf[- ]?strings?\b|\bpython\b.*\b(?:string )?format(?:ting)?\b|\bformat (?:a )?(?:number|float) (?:in )?python\b/i, "f-strings", "python", "name, n, price = \"Ada\", 3, 1234.5\nf\"{name} bought {n} items\"\nf\"{price:,.2f}\"        # 1,234.50\nf\"{n:03d}\"             # 003\nf\"{0.256:.1%}\"         # 25.6%\nf\"{name!r}\"            # 'Ada'\nf\"{name=}\"             # name='Ada'", "");
add("py-requests", /\bpython\b.*\b(?:http|https|get|post) request\b|\bpython requests\b.*\b(?:example|get|post)\b|\bcall (?:an )?api (?:in|with|from) python\b/i, "HTTP request in Python", "python", "# stdlib\nimport json, urllib.request\nwith urllib.request.urlopen(\"https://api.example.com/items\") as r:\n    data = json.load(r)\n\n# requests (pip install requests)\nimport requests\nr = requests.get(\"https://api.example.com/items\", timeout=10)\nr.raise_for_status()\ndata = r.json()\nrequests.post(url, json={\"name\": \"x\"}, timeout=10)", "");
add("py-try-except", /\bpython\b.*\b(?:try|except|exception|error) handling\b|\btry except (?:in )?python\b|\bcatch (?:an )?exception (?:in )?python\b/i, "try / except", "python", "try:\n    value = int(text)\nexcept ValueError as e:\n    print(\"not a number:\", e)\nelse:\n    print(\"ok\", value)     # runs only if no exception\nfinally:\n    cleanup()             # always runs", "");
add("py-dataclass", /\bdataclass(?:es)?\b|\bpython\b.*\b(?:simple )?class (?:with|for) (?:just )?(?:fields|attributes|data)\b/i, "dataclass", "python", "from dataclasses import dataclass, field\n\n@dataclass\nclass Point:\n    x: float\n    y: float = 0.0\n    tags: list[str] = field(default_factory=list)\n\np = Point(1.5)   # Point(x=1.5, y=0.0, tags=[])", "");
add("py-timing", /\btime (?:a )?(?:function|code|block)\b.*\bpython\b|\bpython\b.*\b(?:measure|time) (?:execution|how long)\b|\bhow long (?:does|did) (?:my )?(?:code|function) take (?:in )?python/i, "Time a block of Python", "python", "import time\nt0 = time.perf_counter()\nwork()\nprint(f\"{time.perf_counter() - t0:.3f}s\")\n\n# repeated micro-benchmark\nimport timeit\nprint(timeit.timeit(\"sum(range(1000))\", number=10_000))", "");
add("py-flatten", /\bflatten (?:a )?(?:nested )?list\b.*\bpython\b|\bpython\b.*\bflatten (?:a )?(?:nested )?list\b/i, "Flatten a list of lists", "python", "flat = [x for sub in nested for x in sub]\n# or\nfrom itertools import chain\nflat = list(chain.from_iterable(nested))", "");

// ---------------------------------------------------------------------------
// bash / linux
// ---------------------------------------------------------------------------
add("sh-find-large", /\bfind (?:the )?(?:largest|biggest|big|large) files\b|\bwhat is (?:taking|using|eating) (?:up )?(?:my )?disk space\b|\bdisk usage (?:by|per) (?:folder|directory)\b/i, "Find what is using disk space", "bash", "du -sh * | sort -rh | head -20          # biggest entries in this directory\ndf -h                                   # free space per filesystem\nfind / -xdev -type f -size +500M 2>/dev/null | head   # files over 500 MB", "");
add("sh-find-name", /\bfind (?:a )?files? by name\b|\bfind (?:command )?(?:files? )?(?:named|called|matching)\b|\bsearch for (?:a )?file (?:by name|named)\b/i, "Find files by name", "bash", "find . -name \"*.log\"                 # case-sensitive\nfind . -iname \"readme*\" -type f      # case-insensitive, files only\nfind . -name \"*.tmp\" -delete         # delete matches (careful)", "");
add("sh-grep-recursive", /\bgrep\b.*\b(?:recursive|recursively|all files|directory|folder)\b|\bsearch (?:for )?(?:a )?(?:string|text|word) in (?:all )?files\b|\bfind text in files\b/i, "Search text in files", "bash", "grep -rn \"needle\" .                  # recursive, with line numbers\ngrep -rni --include=\"*.js\" \"needle\" src   # case-insensitive, only .js\ngrep -rl \"needle\" .                  # just the file names", "");
add("sh-port-in-use", /\b(?:what|which|who|find)\b.*\b(?:is )?(?:using|listening on|on|occupying)\b.*\bport\b|\bport (?:already )?in use\b|\bkill (?:the )?process on (?:a )?port\b|\bfree (?:up )?(?:a )?port\b/i, "Find what is listening on a port", "bash", "sudo lsof -i :3000\n# or\nsudo ss -ltnp | grep :3000\n\n# kill it\nkill $(lsof -t -i :3000)", "");
add("sh-chmod", /\bchmod\b.*\b(?:executable|permission|755|644|\+x)\b|\bmake (?:a )?(?:file|script) executable\b|\bfile permissions?\b.*\b(?:linux|chmod|change)\b/i, "File permissions", "bash", "chmod +x script.sh          # make executable\nchmod 644 file.txt          # rw-r--r--\nchmod 755 dir               # rwxr-xr-x\nchmod -R u+rw,go-w dir      # recursive, symbolic\nls -l                       # see them", "Digits: 4 = read, 2 = write, 1 = execute, in the order owner / group / others.");
add("sh-tar", /\b(?:extract|unpack|untar|open)\b.*\b(?:tar|tgz|tar\.gz|tarball)\b|\b(?:create|make)\b.*\btar(?:\.gz| archive|ball)\b|\btar command\b/i, "tar: create and extract", "bash", "tar -czvf archive.tar.gz folder/     # create (gzip)\ntar -xzvf archive.tar.gz             # extract\ntar -xzvf archive.tar.gz -C /dest    # extract elsewhere\ntar -tzvf archive.tar.gz             # list", "c create, x extract, z gzip, v verbose, f file, t list.");
add("sh-unzip", /\bunzip\b.*\b(?:linux|terminal|command|folder)\b|\bzip (?:a )?(?:folder|directory)\b.*\b(?:linux|terminal|command)?|\bzip command\b/i, "zip and unzip", "bash", "zip -r archive.zip folder/\nunzip archive.zip -d /dest\nunzip -l archive.zip          # list", "");
add("sh-ssh-key", /\b(?:generate|create|make|new)\b.*\bssh key\b|\bssh[- ]keygen\b|\bssh key (?:for )?(?:github|server)\b|\bpasswordless ssh\b|\bcopy (?:my )?ssh key to (?:a |the )?server/i, "Generate and install an SSH key", "bash", "ssh-keygen -t ed25519 -C \"you@example.com\"\n# install on a server (passwordless login)\nssh-copy-id user@host\n# or manually append ~/.ssh/id_ed25519.pub to ~/.ssh/authorized_keys on the server\ncat ~/.ssh/id_ed25519.pub     # paste this into GitHub > Settings > SSH keys", "");
add("sh-scp", /\b(?:copy|transfer|send|move)\b.*\b(?:file|folder|directory)\b.*\b(?:to|from|between)\b.*\b(?:server|remote|ssh|another machine)\b|\bscp (?:example|command|syntax)\b/i, "Copy files over SSH", "bash", "scp file.txt user@host:/path/            # local -> remote\nscp user@host:/path/file.txt .           # remote -> local\nscp -r folder/ user@host:/path/          # recursive\n# large or resumable: rsync\nrsync -avz --progress folder/ user@host:/path/folder/", "");
add("sh-loop", /\bbash\b.*\b(?:for )?loop\b|\bloop (?:over|through) (?:files|lines)\b.*\b(?:bash|shell)?|\bfor loop (?:in )?(?:bash|shell|terminal)/i, "Loops in bash", "bash", "for f in *.txt; do echo \"$f\"; done\nfor i in $(seq 1 5); do echo \"$i\"; done\nwhile read -r line; do echo \"$line\"; done < input.txt", "Quote `\"$f\"` so names with spaces survive.");
add("sh-rename-bulk", /\b(?:rename|batch rename|bulk rename)\b.*\b(?:multiple|many|all|bulk|batch)?\b.*\bfiles\b.*\b(?:bash|linux|terminal|extension)?|\bchange (?:the )?extension of (?:all|many) files/i, "Rename many files", "bash", "for f in *.jpeg; do mv -- \"$f\" \"${f%.jpeg}.jpg\"; done\n# with the rename utility (perl)\nrename 's/\\.jpeg$/.jpg/' *.jpeg", "");
add("sh-symlink", /\bsymlink\b|\bsymbolic link\b|\bcreate (?:a )?(?:soft )?link (?:to )?(?:a )?(?:file|folder)/i, "Create a symbolic link", "bash", "ln -s /path/to/target /path/to/link\nls -l /path/to/link      # shows link -> target\nrm /path/to/link         # removes the link only", "");
add("sh-cron", /\bcron(?:tab| job)?\b.*\b(?:run|every|schedule|add|edit|syntax)\b|\bschedule (?:a )?(?:script|command|task)\b.*\b(?:linux|cron|every)\b|\brun (?:a )?script every (?:day|hour|minute|night)/i, "Schedule with cron", "bash", "crontab -e\n# minute hour day-of-month month day-of-week  command\n0 3 * * *   /home/me/backup.sh          # daily at 03:00\n*/15 * * * * /home/me/check.sh          # every 15 minutes\n0 9 * * 1-5 /home/me/report.sh          # weekdays 09:00\ncrontab -l                              # list", "");
add("sh-background", /\brun\b.*\b(?:in the )?background\b.*\b(?:linux|bash|terminal|ssh)?|\bkeep (?:a )?(?:process|script|command) running after (?:i )?(?:log ?out|close|disconnect)\b|\bnohup\b/i, "Run a command in the background", "bash", "nohup ./long-task.sh > task.log 2>&1 &\n# or in a persistent session\ntmux new -s work      # detach: Ctrl+b d, reattach: tmux attach -t work\n# or as a user service (systemd-run)\nsystemd-run --user --unit=task ./long-task.sh", "");
add("sh-sed-replace", /\bsed\b.*\b(?:replace|substitute|in[- ]place)\b|\breplace (?:a )?(?:string|text|word) in (?:a )?file\b.*\b(?:sed|terminal|command line|bash)?|\bfind and replace (?:in )?(?:a )?file (?:from )?(?:the )?(?:terminal|command line)/i, "Find and replace in a file", "bash", "sed -i 's/old/new/g' file.txt              # in place, all occurrences\nsed -i.bak 's/old/new/g' file.txt          # keep a backup\ngrep -rl \"old\" src | xargs sed -i 's/old/new/g'   # many files", "Use a different delimiter for paths: `sed 's#/old/path#/new/path#g'`.");
add("sh-curl", /\bcurl\b.*\b(?:post|json|header|download|example)\b|\bsend (?:a )?(?:post|http) request (?:with |from )?(?:curl|terminal|command line)/i, "curl essentials", "bash", "curl -s https://api.example.com/items | jq .\ncurl -X POST -H \"Content-Type: application/json\" -d '{\"name\":\"x\"}' https://api.example.com/items\ncurl -H \"Authorization: Bearer $TOKEN\" https://api.example.com/me\ncurl -L -o file.zip https://example.com/file.zip     # follow redirects, save\ncurl -I https://example.com                          # headers only", "");
add("sh-history-search", /\bsearch (?:bash |shell |command )?history\b|\bfind (?:a )?(?:previous|old|past) command\b|\bctrl\+?r\b/i, "Search shell history", "bash", "Ctrl+R then type          # reverse search, Ctrl+R again for older matches\nhistory | grep docker\n!42                        # rerun history entry 42\n!!                         # rerun the last command (e.g. sudo !!)", "");
add("sh-disk-free", /\bcheck (?:free |available )?disk space\b|\bhow much (?:disk )?space (?:is )?(?:left|free|available)\b/i, "Check free disk space", "bash", "df -h            # per filesystem\ndf -h .          # the current one\ndu -sh ~/Downloads", "");
add("sh-memory", /\bcheck (?:free |available |used )?(?:ram|memory)\b.*\b(?:linux|terminal|command)?|\bhow much (?:ram|memory) (?:is )?(?:free|used|available)\b/i, "Check memory use", "bash", "free -h\ntop            # or htop; press M to sort by memory\nps aux --sort=-%mem | head", "");
add("sh-env-var", /\bset (?:an )?environment variable\b|\bexport (?:a )?variable\b.*\b(?:bash|shell|permanent)?|\bmake (?:an )?env(?:ironment)? var(?:iable)? permanent/i, "Set an environment variable", "bash", "export API_URL=https://example.com        # this shell session\nAPI_URL=https://example.com ./run.sh      # one command only\n# permanent: add the export line to ~/.bashrc (or ~/.zshrc), then\nsource ~/.bashrc", "");

// ---------------------------------------------------------------------------
// SQL
// ---------------------------------------------------------------------------
add("sql-join", /\bsql\b.*\b(?:inner|left|right|outer)? ?joins?\b|\b(?:inner|left|right|outer) join\b.*\b(?:example|syntax|sql|difference)\b|\bdifference between (?:inner|left) (?:and|vs) (?:left|inner|right) join/i, "SQL joins", "sql", "-- rows with a match in both\nSELECT o.id, c.name FROM orders o INNER JOIN customers c ON c.id = o.customer_id;\n-- all rows from the left, NULLs where no match\nSELECT c.name, o.id FROM customers c LEFT JOIN orders o ON o.customer_id = c.id;\n-- customers with no orders\nSELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL;", "");
add("sql-group-having", /\bsql\b.*\b(?:group by|having|count per|aggregate)\b|\bcount (?:rows |records )?per (?:group|category|user)\b.*\bsql\b|\bhaving clause\b/i, "GROUP BY and HAVING", "sql", "SELECT customer_id, COUNT(*) AS orders, SUM(total) AS spent\nFROM orders\nGROUP BY customer_id\nHAVING COUNT(*) >= 3\nORDER BY spent DESC;", "`WHERE` filters rows before grouping; `HAVING` filters groups after.");
add("sql-duplicates", /\bsql\b.*\b(?:find|delete|remove)\b.*\bduplicates?\b|\b(?:find|delete) duplicate (?:rows|records)\b/i, "Find and delete duplicate rows", "sql", "-- find\nSELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1;\n\n-- delete, keeping the lowest id (PostgreSQL / SQLite)\nDELETE FROM users\nWHERE id NOT IN (SELECT MIN(id) FROM users GROUP BY email);", "");
add("sql-top-n", /\bsql\b.*\b(?:top|first|latest|newest|highest) \d+\b|\blimit (?:and )?offset\b|\bsql (?:pagination|paginate)\b/i, "Top N and pagination", "sql", "SELECT * FROM posts ORDER BY created_at DESC LIMIT 10;\n-- page 3 of 10 per page\nSELECT * FROM posts ORDER BY id LIMIT 10 OFFSET 20;\n-- SQL Server\nSELECT TOP 10 * FROM posts ORDER BY created_at DESC;", "");
add("sql-upsert", /\bupsert\b|\binsert or update\b|\bon conflict\b|\binsert if not exists\b.*\bsql\b/i, "Upsert", "sql", "-- PostgreSQL / SQLite\nINSERT INTO settings (key, value) VALUES ('theme', 'dark')\nON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;\n-- MySQL\nINSERT INTO settings (key, value) VALUES ('theme', 'dark')\nON DUPLICATE KEY UPDATE value = VALUES(value);", "");
add("sql-index", /\b(?:create|add)\b.*\bindex\b.*\b(?:sql|table|column|postgres|mysql)\b|\bsql (?:create )?index\b/i, "Create an index", "sql", "CREATE INDEX idx_orders_customer ON orders (customer_id);\nCREATE UNIQUE INDEX idx_users_email ON users (email);\nCREATE INDEX idx_orders_cust_date ON orders (customer_id, created_at DESC);  -- composite", "Index the columns you filter or join on; each index slows writes a little.");
add("sql-case", /\bsql\b.*\bcase when\b|\bcase (?:statement|expression) (?:in )?sql\b|\bif else (?:in )?sql\b/i, "CASE expression", "sql", "SELECT name,\n  CASE WHEN score >= 90 THEN 'A'\n       WHEN score >= 80 THEN 'B'\n       ELSE 'C' END AS grade\nFROM students;", "");
add("sql-date-filter", /\bsql\b.*\b(?:last|past) (?:\d+ )?(?:days?|weeks?|months?)\b|\brows? from (?:the )?last (?:\d+ )?(?:days?|weeks?|months?)\b.*\bsql\b|\bsql (?:filter|where) (?:by )?date\b/i, "Filter by recent dates", "sql", "-- PostgreSQL\nSELECT * FROM events WHERE created_at >= NOW() - INTERVAL '7 days';\n-- MySQL\nSELECT * FROM events WHERE created_at >= NOW() - INTERVAL 7 DAY;\n-- SQLite\nSELECT * FROM events WHERE created_at >= datetime('now', '-7 days');", "");

// ---------------------------------------------------------------------------
// Docker
// ---------------------------------------------------------------------------
add("docker-cleanup", /\bdocker\b.*\b(?:clean ?up|prune|free (?:up )?space|remove (?:all|unused|dangling))\b|\bremove all docker (?:images|containers)\b/i, "Clean up Docker", "bash", "docker system prune -a --volumes    # everything unused (asks first)\ndocker container prune               # stopped containers\ndocker image prune -a                # unused images\ndocker volume prune                  # unused volumes\ndocker system df                     # what is using space", "");
add("docker-shell", /\bdocker\b.*\b(?:shell|bash|sh|exec|get into|enter|inside|attach)\b.*\bcontainer\b|\b(?:shell|bash) into (?:a )?(?:running )?(?:docker )?container\b|^docker exec(?: -it)?(?: bash| sh)?$/i, "Shell into a running container", "bash", "docker exec -it <container> bash     # or sh if bash is missing\ndocker ps                            # to find the name/id", "");
add("docker-logs", /\bdocker\b.*\blogs?\b.*\b(?:follow|tail|container|see|view)\b|\bsee (?:the )?(?:docker )?container logs\b/i, "Container logs", "bash", "docker logs -f --tail 100 <container>\ndocker compose logs -f web", "");
add("docker-copy", /\bdocker\b.*\b(?:copy|cp)\b.*\b(?:file|from|to|out of|into)\b.*\bcontainer\b|\bcopy (?:a )?file (?:out of|from|into) (?:a )?(?:docker )?container/i, "Copy files to/from a container", "bash", "docker cp <container>:/app/out.log ./out.log     # out\ndocker cp ./config.yml <container>:/app/         # in", "");
add("docker-run-basic", /\bdocker run\b.*\b(?:port|volume|detach|background|env|example)\b|\brun (?:a )?(?:docker )?container (?:with|in|on)\b/i, "docker run essentials", "bash", "docker run -d --name web -p 8080:80 -v $(pwd)/site:/usr/share/nginx/html:ro -e TZ=UTC --restart unless-stopped nginx:alpine\n# -d detached, -p host:container, -v host:container, -e env var\ndocker stop web && docker rm web", "");
add("docker-compose-basic", /\bdocker[- ]compose\b.*\b(?:example|basic|template|minimal|file|yml|yaml)\b|\bwrite (?:a )?docker[- ]compose\b/i, "Minimal docker compose file", "yaml", "services:\n  web:\n    build: .\n    ports: [\"3000:3000\"]\n    environment:\n      DATABASE_URL: postgres://app:secret@db:5432/app\n    depends_on: [db]\n  db:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_USER: app\n      POSTGRES_PASSWORD: secret\n    volumes: [\"pgdata:/var/lib/postgresql/data\"]\nvolumes:\n  pgdata:", "Run with `docker compose up -d`, stop with `docker compose down`.");
add("dockerfile-node", /\bdockerfile\b.*\b(?:node|express|next)\b|\b(?:node|express) (?:app )?dockerfile\b/i, "Dockerfile for a Node app", "dockerfile", "FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY . .\nEXPOSE 3000\nUSER node\nCMD [\"node\", \"server.js\"]", "Copy package files first so `npm ci` is cached until dependencies change.");
add("dockerfile-python", /\bdockerfile\b.*\b(?:python|flask|django|fastapi)\b|\b(?:python|flask|fastapi) (?:app )?dockerfile\b/i, "Dockerfile for a Python app", "dockerfile", "FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD [\"python\", \"app.py\"]", "");

// ---------------------------------------------------------------------------
// security / networking
// ---------------------------------------------------------------------------
add("sec-hash-password", /\b(?:hash|store|save)\b.*\bpasswords?\b.*\b(?:securely|safely|properly|correctly|python|node|js|javascript|php)?|\bpassword hashing\b|\bbcrypt (?:example|python|node)\b/i, "Hash passwords properly", "python", "# Python (pip install argon2-cffi)  -- or bcrypt\nfrom argon2 import PasswordHasher\nph = PasswordHasher()\nh = ph.hash(password)        # store h\nph.verify(h, attempt)        # raises on mismatch\n\n# Node\n# const bcrypt = require(\"bcrypt\"); const h = await bcrypt.hash(pw, 12); await bcrypt.compare(pw, h);", "Never use MD5/SHA-1/SHA-256 alone for passwords: they are fast, so brute force is cheap. Argon2id or bcrypt are slow by design and salt automatically.");
add("sec-random-secret", /\bgenerate (?:a )?(?:random |secure )?(?:secret|token|api key|password)\b.*\b(?:terminal|command line|linux|python|node|openssl)?|\bopenssl rand\b|\brandom (?:secret|token|hex) (?:in|from) (?:the )?(?:terminal|shell)/i, "Generate a random secret", "bash", "openssl rand -hex 32                # 64 hex chars\nopenssl rand -base64 32\nhead -c 32 /dev/urandom | base64\n# Python: python3 -c 'import secrets; print(secrets.token_hex(32))'\n# Node:   node -e 'console.log(require(\"crypto\").randomBytes(32).toString(\"hex\"))'", "");
add("sec-check-cert", /\bcheck (?:an? )?(?:ssl|tls) cert(?:ificate)?\b|\bcert(?:ificate)? expir(?:y|ation)\b.*\b(?:check|see|command)|\bview (?:a )?(?:site'?s |server'?s )?(?:ssl|tls) certificate/i, "Check a site's TLS certificate", "bash", "openssl s_client -connect example.com:443 -servername example.com </dev/null 2>/dev/null | openssl x509 -noout -dates -subject -issuer\n# just the expiry\necho | openssl s_client -connect example.com:443 -servername example.com 2>/dev/null | openssl x509 -noout -enddate", "");
add("sec-self-signed", /\bself[- ]signed cert(?:ificate)?\b.*\b(?:create|generate|make|openssl)?|\b(?:create|generate|make) (?:a )?self[- ]signed\b|\blocal (?:https|ssl|tls) cert(?:ificate)? for (?:dev|localhost)/i, "Create a self-signed certificate", "bash", "openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes \\\n  -keyout key.pem -out cert.pem -subj \"/CN=localhost\" \\\n  -addext \"subjectAltName=DNS:localhost,IP:127.0.0.1\"", "For local development use `mkcert` instead; browsers trust it without warnings.");
add("net-my-ip-cli", /\b(?:find|get|show|check|see)\b.*\b(?:my |the |local |private |lan )?ip address\b.*\b(?:linux|terminal|command|cli|mac)?|\bwhat(?:'s| is) my (?:local |private |lan |public )?ip(?: address)?\b/i, "Find your IP address", "bash", "ip -4 addr show | grep inet       # local (LAN) addresses\nhostname -I                       # short form\ncurl -s https://ifconfig.me       # public IP (asks an outside service)", "DI itself cannot see your network; these commands run on your machine.");
add("net-test-port", /\b(?:test|check|verify)\b.*\b(?:if )?(?:a )?port (?:is )?(?:open|reachable|listening)\b|\bport (?:open )?check (?:from )?(?:the )?(?:terminal|command line)|\btelnet (?:alternative|to test)/i, "Test whether a port is open", "bash", "nc -zv host 443                     # netcat\ntimeout 3 bash -c '</dev/tcp/host/443' && echo open || echo closed\nnmap -p 443 host                    # if nmap is installed", "Only scan hosts you own or have permission to test.");
add("net-dns-lookup", /\bdns lookup\b|\blook ?up (?:the )?(?:dns|mx|txt|a) records?\b|\bcheck (?:the )?dns (?:records?|of|for)\b|\bdig (?:command|example)\b|\bnslookup\b/i, "DNS lookup", "bash", "dig example.com A +short\ndig example.com MX\ndig example.com TXT\ndig @1.1.1.1 example.com          # ask a specific resolver\nnslookup example.com", "");
add("net-trace", /\btraceroute\b|\btrace (?:the )?route\b|\bwhy is (?:my )?(?:connection|network) slow to\b/i, "Trace the route to a host", "bash", "traceroute example.com\nmtr example.com          # live, combines ping + traceroute\nping -c 5 example.com", "");
add("net-headers", /\b(?:see|view|show|check|get)\b.*\b(?:http )?(?:response )?headers\b.*\b(?:curl|site|url|website|terminal)?|\bsecurity headers (?:check|of)\b/i, "See a site's HTTP headers", "bash", "curl -sI https://example.com\n# follow redirects and show each hop's headers\ncurl -sIL https://example.com", "Look for Strict-Transport-Security, Content-Security-Policy, X-Content-Type-Options and X-Frame-Options.");
add("sec-gitignore-secrets", /\b(?:accidentally|by mistake)\b.*\b(?:committed|pushed)\b.*\b(?:secret|key|password|token|\.env)\b|\bremove (?:a )?(?:secret|api key|password|\.env) from (?:git )?history\b/i, "A secret was committed", "bash", "# 1. rotate the secret first: treat it as leaked\n# 2. stop tracking the file\necho \".env\" >> .gitignore && git rm --cached .env && git commit -m \"untrack .env\"\n# 3. purge it from history (rewrites every commit; coordinate with your team)\n#    pip install git-filter-repo\ngit filter-repo --path .env --invert-paths\ngit push --force-with-lease --all", "Rotating the credential is the only real fix; history rewriting stops future clones from seeing it but anyone who already fetched still has it.");

// ---------------------------------------------------------------------------
// regex / misc dev
// ---------------------------------------------------------------------------
add("regex-email", /\bregex\b.*\b(?:for |to (?:match|validate) )?(?:an )?email\b|\bvalidate (?:an )?email (?:address )?(?:with |using )?regex\b/i, "Email regex (practical)", "javascript", "const EMAIL = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\nEMAIL.test(\"a.b@example.com\"); // true", "A full RFC 5322 regex is huge and still not a deliverability check; validate the shape, then send a confirmation email.");
add("npm-update", /\b(?:update|upgrade)\b.*\b(?:npm )?(?:packages|dependencies|deps)\b.*\b(?:npm|node|package\.json)?|\bnpm (?:update|upgrade|outdated)\b/i, "Update npm dependencies", "bash", "npm outdated                         # what is behind\nnpm update                           # within the ranges in package.json\nnpx npm-check-updates -u && npm install   # bump the ranges themselves (majors too)", "");
add("npm-init-project", /\b(?:start|init|initialize|create|set ?up|bootstrap)\b.*\b(?:new )?(?:node|npm|javascript|js) project\b/i, "Start a Node project", "bash", "mkdir app && cd app\nnpm init -y\nnpm pkg set type=module\nnpm install express\necho 'node_modules\\n.env' > .gitignore\ngit init", "");
add("http-status-codes", /\b(?:list of |common )?http status codes\b|\bwhat (?:do|does) (?:the )?(?:http )?status codes? mean\b/i, "Common HTTP status codes", "text", "200 OK               201 Created          204 No Content\n301 Moved Permanently 302 Found            304 Not Modified\n400 Bad Request      401 Unauthorized     403 Forbidden\n404 Not Found        405 Method Not Allowed 409 Conflict\n422 Unprocessable    429 Too Many Requests\n500 Internal Error   502 Bad Gateway      503 Unavailable      504 Gateway Timeout", "401 means not authenticated (who are you?); 403 means authenticated but not allowed.");
add("json-vs-yaml", /\bjson (?:to|vs|versus|or) yaml\b|\byaml (?:to|vs|versus|or) json\b|\bconvert (?:json|yaml) (?:to|into) (?:yaml|json)\b/i, "JSON to YAML", "bash", "# yq (https://github.com/mikefarah/yq)\nyq -P '.' file.json > file.yaml        # JSON -> YAML\nyq -o=json '.' file.yaml > file.json   # YAML -> JSON\n# Python\npython3 -c 'import sys,json,yaml; print(yaml.safe_dump(json.load(sys.stdin)))' < file.json", "DI does not run converters on your document offline; these commands do it on your machine.");

// ---------------------------------------------------------------------------
export const ENTRIES = H;
// words the typo corrector must leave alone ("div" is not "dig", "npm" is not "nap")
// every word an entry's pattern or title mentions is vocabulary too ("footer", "params", "ellipsis")
const PATTERN_WORDS = [...new Set(H.flatMap((h) => (h.re.source + " " + h.title).toLowerCase().match(/[a-z][a-z0-9]{2,}/g) || []))];
export const VOCAB = [...PATTERN_WORDS, "div", "css", "html", "js", "javascript", "node", "npm", "npx", "git", "commit", "commits", "stash", "branch", "rebase", "merge", "amend", "unstage", "untrack", "cherry", "squash", "tag", "tags", "clone", "diff", "remote", "push", "pull", "sql", "yaml", "yml", "json", "docker", "dockerfile", "compose", "container", "containers", "bash", "shell", "grep", "sed", "awk", "curl", "wget", "ssh", "scp", "rsync", "tar", "tgz", "zip", "unzip", "chmod", "chown", "cron", "crontab", "nohup", "tmux", "symlink", "venv", "pip", "argparse", "dataclass", "dataclasses", "fstring", "fstrings", "enumerate", "zip", "lambda", "regex", "fetch", "debounce", "throttle", "clipboard", "localstorage", "urlsearchparams", "promise", "promises", "async", "await", "upsert", "index", "join", "joins", "flask", "django", "fastapi", "express", "nginx", "postgres", "postgresql", "mysql", "sqlite", "redis", "mongodb", "kubernetes", "openssl", "cert", "certificate", "tls", "ssl", "bcrypt", "argon2", "dig", "nslookup", "traceroute", "mtr", "ping", "nmap", "netcat", "lsof", "df", "du", "env", "dotenv", "viewport", "flexbox", "grid", "ellipsis", "scrollbar", "svg", "api", "http", "https", "ip", "dns", "port", "url", "uuid", "sudo", "linux", "ubuntu", "mac", "macos", "windows", "vim", "nano", "python", "python3", "pip3", "pipenv", "poetry", "requirements"];
export function ask(input) {
  const s = String(input || "").trim().replace(/\s+/g, " ");
  if (s.length < 6 || s.length > 200) return null;
  // strip the question frame so "how do i undo the last git commit" and "undo last git commit" match alike
  const core = s.replace(/^(?:how (?:do|can|would|should) (?:i|you|we|one)|how to|what(?:'s| is) the (?:command|way|syntax) (?:to|for)|show me how to|i want to|i need to|help me)\s+/i, "").replace(/[?.!]+$/, "");
  const hits = H.filter((h) => h.re.test(core) || h.re.test(s));
  if (!hits.length) return null;
  return { id: hits[0].id, alt: hits.slice(1, 4).map((h) => h.id), query: s };
}
export function run(q) {
  if (!q) return { ok: false, error: "not a how-to I have" };
  const e = H.find((h) => h.id === q.id);
  return e ? { ok: true, id: e.id, title: e.title, lang: e.lang, code: e.code, body: e.body, note: e.note, alt: q.alt.map((id) => H.find((h) => h.id === id)).filter(Boolean).map((h) => h.title), value: null } : { ok: false, error: "not a how-to I have" };
}
export function say(res) {
  if (!res.ok) return { title: "How-to", body: res.error, result: res };
  const also = res.alt.length ? "\n\nRelated: " + res.alt.join("; ") + "." : "";
  return { title: res.title, body: (res.body ? res.body + "\n\n" : "") + "```" + res.lang + "\n" + res.code + "\n```" + also, note: (res.note ? res.note + " " : "") + "Curated snippet from DI's how-to library (hand-written and reviewed, not generated).", result: res };
}
