// People, animals and animal records for the offline deterministic Q&A engine.
// Curated, conservative data: only well-established facts; null means "not confidently known,
// do not state". Living people carry only stable facts (birth year, what they are known for).
// PEOPLE row: [display name, life years, role phrase, 1-3 sentence summary]
// Deterministic, no imports.

export const PEOPLE = {
  // ---- Science and mathematics ----
  "albert einstein": ["Albert Einstein", "1879-1955", "German-born theoretical physicist", "He developed the theory of relativity (special 1905, general 1915) and explained the photoelectric effect, for which he won the 1921 Nobel Prize in Physics. E = mc^2 comes from his 1905 work."],
  "isaac newton": ["Isaac Newton", "1643-1727", "English mathematician and physicist", "In his Principia (1687) he set out the three laws of motion and the law of universal gravitation. He also developed calculus (independently of Leibniz) and made major discoveries in optics."],
  "charles darwin": ["Charles Darwin", "1809-1882", "English naturalist", "He proposed the theory of evolution by natural selection in On the Origin of Species (1859). His ideas grew from observations made on the voyage of HMS Beagle (1831-1836)."],
  "marie curie": ["Marie Curie", "1867-1934", "Polish-born French physicist and chemist", "She pioneered research on radioactivity and discovered the elements polonium and radium. She was the first woman to win a Nobel Prize and the only person to win Nobel Prizes in two different sciences (Physics 1903, Chemistry 1911)."],
  "galileo galilei": ["Galileo Galilei", "1564-1642", "Italian astronomer and physicist", "He improved the telescope and discovered the four largest moons of Jupiter in 1610. His support for the Sun-centered model of the solar system led to his trial by the Roman Inquisition in 1633."],
  "nikola tesla": ["Nikola Tesla", "1856-1943", "Serbian-American inventor and electrical engineer", "He developed the alternating current (AC) induction motor and polyphase AC systems that underpin modern electric power. He also invented the Tesla coil."],
  "thomas edison": ["Thomas Edison", "1847-1931", "American inventor and businessman", "He invented the phonograph (1877) and developed a practical incandescent light bulb (1879). He held over 1,000 US patents and ran one of the first industrial research labs, at Menlo Park."],
  "stephen hawking": ["Stephen Hawking", "1942-2018", "English theoretical physicist and cosmologist", "He predicted that black holes emit radiation (Hawking radiation) and wrote the best-seller A Brief History of Time (1988). He did most of his work while living with motor neurone disease (ALS)."],
  "nicolaus copernicus": ["Nicolaus Copernicus", "1473-1543", "Polish Renaissance astronomer", "He proposed that the Earth and planets orbit the Sun rather than the Earth being the center of the universe. His book De revolutionibus was published in 1543, the year he died."],
  "johannes kepler": ["Johannes Kepler", "1571-1630", "German astronomer and mathematician", "He discovered the three laws of planetary motion, showing that planets move in elliptical orbits around the Sun."],
  "michael faraday": ["Michael Faraday", "1791-1867", "English scientist", "He discovered electromagnetic induction (1831), the principle behind electric generators and transformers, and built early electric motors. He also made foundational discoveries in electrochemistry."],
  "james clerk maxwell": ["James Clerk Maxwell", "1831-1879", "Scottish physicist", "His equations unified electricity, magnetism and light into a single theory of electromagnetism. He showed that light is an electromagnetic wave."],
  "louis pasteur": ["Louis Pasteur", "1822-1895", "French chemist and microbiologist", "He helped establish the germ theory of disease and invented pasteurization. He developed vaccines for anthrax and rabies."],
  "gregor mendel": ["Gregor Mendel", "1822-1884", "Austrian monk and scientist", "His experiments with pea plants revealed the basic laws of heredity, and he is known as the father of genetics."],
  "alan turing": ["Alan Turing", "1912-1954", "English mathematician and computer scientist", "He described the Turing machine (1936), a foundation of computer science, and helped break German Enigma codes at Bletchley Park in World War II. He also proposed the Turing test for machine intelligence (1950)."],
  "ada lovelace": ["Ada Lovelace", "1815-1852", "English mathematician and writer", "Her 1843 notes on Charles Babbage's Analytical Engine included what is considered the first published computer algorithm. She is often called the first computer programmer."],
  "niels bohr": ["Niels Bohr", "1885-1962", "Danish physicist", "He developed the Bohr model of the atom (1913), with electrons in fixed energy levels, and was a founder of quantum theory. He won the 1922 Nobel Prize in Physics."],
  "max planck": ["Max Planck", "1858-1947", "German theoretical physicist", "He originated quantum theory in 1900 by proposing that energy is emitted in discrete packets (quanta). He won the 1918 Nobel Prize in Physics."],
  "richard feynman": ["Richard Feynman", "1918-1988", "American theoretical physicist", "He helped develop quantum electrodynamics and invented Feynman diagrams, sharing the 1965 Nobel Prize in Physics. He was also a celebrated teacher and popular writer."],
  "rosalind franklin": ["Rosalind Franklin", "1920-1958", "English chemist and X-ray crystallographer", "Her X-ray diffraction images of DNA, including Photo 51, were key evidence for the double-helix structure described by Watson and Crick in 1953."],
  "alexander fleming": ["Alexander Fleming", "1881-1955", "Scottish physician and microbiologist", "He discovered penicillin in 1928, the first widely used antibiotic. He shared the 1945 Nobel Prize in Physiology or Medicine."],
  "dmitri mendeleev": ["Dmitri Mendeleev", "1834-1907", "Russian chemist", "He created the periodic table of the elements (1869) and used it to predict the properties of elements not yet discovered."],
  "archimedes": ["Archimedes", "c. 287-212 BC", "ancient Greek mathematician, physicist and inventor from Syracuse", "He discovered the principle of buoyancy (Archimedes' principle), explained the lever, and gave an accurate approximation of pi. He is considered one of the greatest mathematicians of antiquity."],
  "euclid": ["Euclid", "fl. c. 300 BC", "ancient Greek mathematician", "His Elements organized geometry into a logical system of definitions, axioms and proofs, and was used as a textbook for over 2,000 years. He is called the father of geometry."],
  "pythagoras": ["Pythagoras", "c. 570-495 BC", "ancient Greek philosopher and mathematician", "He founded a philosophical school in southern Italy, and the Pythagorean theorem (a^2 + b^2 = c^2 for right triangles) bears his name."],
  "carl sagan": ["Carl Sagan", "1934-1996", "American astronomer and science communicator", "He made astronomy popular through the TV series Cosmos (1980) and many books, and worked on NASA planetary missions including the Voyager Golden Record."],
  "jane goodall": ["Jane Goodall", "1934-2025", "English primatologist and conservationist", "Beginning in 1960 at Gombe in Tanzania, she studied wild chimpanzees for decades and discovered that they make and use tools. She became one of the world's best-known conservationists."],
  "edwin hubble": ["Edwin Hubble", "1889-1953", "American astronomer", "He showed that there are galaxies beyond the Milky Way and found that galaxies are moving away from us, evidence that the universe is expanding. The Hubble Space Telescope is named after him."],
  "j robert oppenheimer": ["J. Robert Oppenheimer", "1904-1967", "American theoretical physicist", "He directed the Los Alamos Laboratory during the Manhattan Project, which built the first atomic bombs in World War II. He is often called the father of the atomic bomb."],
  "enrico fermi": ["Enrico Fermi", "1901-1954", "Italian-American physicist", "He built the first nuclear reactor, Chicago Pile-1, which achieved a self-sustaining chain reaction in 1942. He won the 1938 Nobel Prize in Physics."],
  "werner heisenberg": ["Werner Heisenberg", "1901-1976", "German theoretical physicist", "He was a founder of quantum mechanics and formulated the uncertainty principle (1927). He won the 1932 Nobel Prize in Physics."],
  "erwin schrodinger": ["Erwin Schrodinger", "1887-1961", "Austrian physicist", "He formulated the Schrodinger equation (1926), the central equation of wave mechanics in quantum theory, and proposed the famous Schrodinger's cat thought experiment. He shared the 1933 Nobel Prize in Physics."],
  "leonhard euler": ["Leonhard Euler", "1707-1783", "Swiss mathematician", "One of the most prolific mathematicians in history, he made major contributions to calculus, graph theory and number theory. He popularized notation such as e, i and f(x), and Euler's identity bears his name."],
  "carl friedrich gauss": ["Carl Friedrich Gauss", "1777-1855", "German mathematician and physicist", "Called the prince of mathematicians, he made fundamental contributions to number theory, statistics (the normal or Gaussian distribution), astronomy and magnetism."],
  "srinivasa ramanujan": ["Srinivasa Ramanujan", "1887-1920", "Indian mathematician", "Largely self-taught, he produced thousands of original results in number theory, infinite series and continued fractions, and worked with G. H. Hardy at Cambridge."],
  "gottfried wilhelm leibniz": ["Gottfried Wilhelm Leibniz", "1646-1716", "German mathematician and philosopher", "He developed calculus independently of Newton, and his notation (such as dx and the integral sign) is still used today. He also worked on binary arithmetic and philosophy."],
  "rachel carson": ["Rachel Carson", "1907-1964", "American marine biologist and writer", "Her book Silent Spring (1962) exposed the dangers of pesticides such as DDT and helped launch the modern environmental movement."],
  "alfred nobel": ["Alfred Nobel", "1833-1896", "Swedish chemist, engineer and inventor", "He invented dynamite (1867). His will created the Nobel Prizes, first awarded in 1901."],
  "antoine lavoisier": ["Antoine Lavoisier", "1743-1794", "French chemist", "Known as the father of modern chemistry, he established the law of conservation of mass and named oxygen and hydrogen. He was executed by guillotine during the French Revolution."],
  "edward jenner": ["Edward Jenner", "1749-1823", "English physician", "He developed the smallpox vaccine in 1796 using material from cowpox, pioneering the concept of vaccination."],
  "hippocrates": ["Hippocrates", "c. 460-370 BC", "ancient Greek physician", "Known as the father of medicine, he helped separate medicine from religion and superstition. The Hippocratic Oath is traditionally attributed to him."],
  "katherine johnson": ["Katherine Johnson", "1918-2020", "American mathematician at NASA", "Her orbital calculations were critical to early US crewed spaceflights, including John Glenn's 1962 orbit of the Earth. Her story was told in the book and film Hidden Figures."],
  "c v raman": ["C. V. Raman", "1888-1970", "Indian physicist", "He discovered the Raman effect, the scattering of light that changes its wavelength, and won the 1930 Nobel Prize in Physics, the first Asian to win a Nobel in the sciences."],
  "sigmund freud": ["Sigmund Freud", "1856-1939", "Austrian neurologist", "He founded psychoanalysis and developed ideas about the unconscious mind, dreams and repression, including in The Interpretation of Dreams."],
  "charles babbage": ["Charles Babbage", "1791-1871", "English mathematician and engineer", "He designed the Difference Engine and the Analytical Engine, mechanical computers that anticipated modern computing, and is called the father of the computer."],

  // ---- Inventors and engineers ----
  "alexander graham bell": ["Alexander Graham Bell", "1847-1922", "Scottish-born inventor and scientist", "He was awarded the first US patent for the telephone in 1876 and co-founded the Bell Telephone Company."],
  "wright brothers": ["The Wright brothers", "Wilbur 1867-1912, Orville 1871-1948", "American aviation pioneers", "Wilbur and Orville Wright made the first controlled, sustained, powered airplane flight on December 17, 1903, near Kitty Hawk, North Carolina."],
  "johannes gutenberg": ["Johannes Gutenberg", "c. 1400-1468", "German goldsmith and printer", "He introduced movable-type printing to Europe around 1440 to 1450, and his Gutenberg Bible (c. 1455) was among the first major books printed this way. His press helped spread knowledge across Europe."],
  "james watt": ["James Watt", "1736-1819", "Scottish inventor and engineer", "His improvements to the steam engine, especially the separate condenser, made it far more efficient and helped drive the Industrial Revolution. The unit of power, the watt, is named after him."],
  "guglielmo marconi": ["Guglielmo Marconi", "1874-1937", "Italian inventor and electrical engineer", "He pioneered long-distance radio communication and sent a radio signal across the Atlantic in 1901. He shared the 1909 Nobel Prize in Physics."],
  "henry ford": ["Henry Ford", "1863-1947", "American industrialist", "He founded the Ford Motor Company, introduced the Model T in 1908, and adopted the moving assembly line in 1913, making cars affordable for ordinary people."],
  "tim berners-lee": ["Tim Berners-Lee", "born 1955", "English computer scientist", "He invented the World Wide Web in 1989 while working at CERN, creating HTML, HTTP and URLs."],
  "benjamin franklin": ["Benjamin Franklin", "1706-1790", "American polymath and Founding Father", "He was a writer, printer, scientist and diplomat who helped draft and signed the Declaration of Independence. His kite experiment (1752) showed that lightning is electricity, and he invented the lightning rod and bifocals."],
  "samuel morse": ["Samuel Morse", "1791-1872", "American inventor and painter", "He co-developed Morse code and helped develop the electric telegraph; his 1844 message 'What hath God wrought' opened the first US telegraph line."],
  "karl benz": ["Karl Benz", "1844-1929", "German engineer", "He built the Benz Patent-Motorwagen (patented 1886), widely regarded as the first practical automobile powered by an internal combustion engine."],

  // ---- Leaders and rulers ----
  "abraham lincoln": ["Abraham Lincoln", "1809-1865", "16th president of the United States", "He led the Union through the American Civil War, issued the Emancipation Proclamation (1863), and pushed for the 13th Amendment abolishing slavery. He was assassinated in April 1865."],
  "george washington": ["George Washington", "1732-1799", "1st president of the United States", "He commanded the Continental Army in the American Revolutionary War and served as the first US president from 1789 to 1797."],
  "thomas jefferson": ["Thomas Jefferson", "1743-1826", "3rd president of the United States", "He was the principal author of the Declaration of Independence (1776) and, as president (1801-1809), made the Louisiana Purchase (1803)."],
  "napoleon bonaparte": ["Napoleon Bonaparte", "1769-1821", "French military leader and emperor", "He rose to power after the French Revolution, crowned himself Emperor of the French in 1804, and conquered much of Europe. He created the Napoleonic Code and was finally defeated at Waterloo in 1815."],
  "julius caesar": ["Julius Caesar", "100-44 BC", "Roman general and statesman", "He conquered Gaul, crossed the Rubicon in 49 BC to start a civil war, and became dictator of Rome. He was assassinated on the Ides of March (March 15), 44 BC."],
  "alexander the great": ["Alexander the Great", "356-323 BC", "king of Macedon", "Tutored by Aristotle, he built one of the largest empires of the ancient world, stretching from Greece and Egypt to northwest India, before dying at 32."],
  "cleopatra": ["Cleopatra VII", "69-30 BC", "last active ruler of Ptolemaic Egypt", "She allied with Julius Caesar and then Mark Antony to protect Egypt's power. After their defeat by Octavian she died in 30 BC, and Egypt became a Roman province."],
  "winston churchill": ["Winston Churchill", "1874-1965", "British prime minister", "He led the United Kingdom through most of World War II as prime minister (1940-1945) and served again from 1951 to 1955. He won the 1953 Nobel Prize in Literature."],
  "franklin d roosevelt": ["Franklin D. Roosevelt", "1882-1945", "32nd president of the United States", "He served from 1933 until his death in 1945, leading the US through the Great Depression with the New Deal and through most of World War II. He is the only president elected four times."],
  "theodore roosevelt": ["Theodore Roosevelt", "1858-1919", "26th president of the United States", "President from 1901 to 1909, he promoted conservation and national parks, broke up monopolies, and won the 1906 Nobel Peace Prize."],
  "john f kennedy": ["John F. Kennedy", "1917-1963", "35th president of the United States", "President from 1961, he handled the Cuban Missile Crisis (1962) and launched the goal of landing a man on the Moon. He was assassinated in Dallas on November 22, 1963."],
  "ronald reagan": ["Ronald Reagan", "1911-2004", "40th president of the United States", "A former actor and governor of California, he was president from 1981 to 1989, a period that saw tax cuts, a military buildup and easing Cold War tensions with the Soviet Union."],
  "barack obama": ["Barack Obama", "born 1961", "44th president of the United States", "He served as president from 2009 to 2017 and was the first African American to hold the office. He won the 2009 Nobel Peace Prize."],
  "queen victoria": ["Queen Victoria", "1819-1901", "queen of the United Kingdom", "She reigned from 1837 to 1901, a period called the Victorian era, when the British Empire reached its greatest extent."],
  "elizabeth i": ["Elizabeth I", "1533-1603", "queen of England and Ireland", "She reigned from 1558 to 1603, a period of English cultural flourishing known as the Elizabethan era, and her navy defeated the Spanish Armada in 1588."],
  "elizabeth ii": ["Elizabeth II", "1926-2022", "queen of the United Kingdom", "She reigned from 1952 until her death in 2022, making her the longest-reigning British monarch, at 70 years."],
  "genghis khan": ["Genghis Khan", "c. 1162-1227", "founder of the Mongol Empire", "He united the Mongol tribes in 1206 and launched conquests that created what became the largest contiguous land empire in history."],
  "nelson mandela": ["Nelson Mandela", "1918-2013", "South African anti-apartheid leader and president", "He spent 27 years in prison for opposing apartheid, then became South Africa's first Black president (1994-1999). He shared the 1993 Nobel Peace Prize."],
  "mahatma gandhi": ["Mahatma Gandhi", "1869-1948", "leader of the Indian independence movement", "He led India's struggle for independence from British rule using nonviolent civil disobedience, including the Salt March of 1930. He was assassinated on January 30, 1948."],
  "jawaharlal nehru": ["Jawaharlal Nehru", "1889-1964", "first prime minister of India", "A leader of the independence movement, he served as India's first prime minister from 1947 until his death in 1964."],
  "b r ambedkar": ["B. R. Ambedkar", "1891-1956", "Indian jurist, economist and social reformer", "He chaired the drafting committee of the Constitution of India and campaigned against caste discrimination, especially for the rights of Dalits."],
  "vallabhbhai patel": ["Sardar Vallabhbhai Patel", "1875-1950", "Indian independence leader and statesman", "As India's first deputy prime minister and home minister, he led the integration of over 500 princely states into the new Indian union. The Statue of Unity honors him."],
  "bhagat singh": ["Bhagat Singh", "1907-1931", "Indian revolutionary", "A leading figure in the armed struggle against British rule, he was executed in 1931 at the age of 23 and is remembered as a national hero."],
  "apj abdul kalam": ["A. P. J. Abdul Kalam", "1931-2015", "Indian aerospace scientist and 11th president of India", "Known as the Missile Man of India for his work on missile and space programs, he served as president from 2002 to 2007."],
  "swami vivekananda": ["Swami Vivekananda", "1863-1902", "Indian Hindu monk and philosopher", "He introduced Vedanta and yoga to Western audiences, most famously at the 1893 Parliament of the World's Religions in Chicago."],
  "shivaji": ["Shivaji", "1630-1680", "Indian warrior king", "He founded the Maratha kingdom (later empire) in western India and was crowned Chhatrapati in 1674."],
  "ashoka": ["Ashoka", "c. 304-232 BC", "emperor of the Maurya Empire in India", "After the bloody Kalinga war he embraced Buddhism and nonviolence, spreading his ideals through rock and pillar edicts. His lion capital is India's national emblem."],
  "akbar": ["Akbar", "1542-1605", "Mughal emperor", "Ruling from 1556 to 1605, he greatly expanded the Mughal Empire across India and was known for religious tolerance and strong administration."],
  "charlemagne": ["Charlemagne", "c. 747-814", "king of the Franks and emperor", "He united much of western Europe and was crowned emperor by the pope in 800. His reign encouraged a revival of learning known as the Carolingian Renaissance."],
  "augustus": ["Augustus", "63 BC-AD 14", "first Roman emperor", "Born Octavian, Julius Caesar's adopted heir, he defeated Mark Antony and Cleopatra and became Rome's first emperor in 27 BC, beginning a long era of relative peace."],
  "peter the great": ["Peter the Great", "1672-1725", "tsar and first emperor of Russia", "He modernized Russia along Western European lines, built a navy, and founded St. Petersburg in 1703."],
  "catherine the great": ["Catherine the Great", "1729-1796", "empress of Russia", "She ruled from 1762 to 1796, expanding Russia's territory and promoting Enlightenment ideas, the arts and education."],
  "louis xiv": ["Louis XIV", "1638-1715", "king of France", "Known as the Sun King, he reigned for 72 years (1643-1715), one of the longest reigns in European history, and built the Palace of Versailles."],
  "ramses ii": ["Ramses II", "c. 1303-1213 BC", "pharaoh of ancient Egypt", "Also called Ramesses the Great, he ruled for about 66 years (c. 1279-1213 BC) and built monuments such as the temples of Abu Simbel."],
  "tutankhamun": ["Tutankhamun", "c. 1341-1323 BC", "pharaoh of ancient Egypt", "A young pharaoh who died around age 19, he became famous when Howard Carter discovered his nearly intact tomb in 1922."],
  "qin shi huang": ["Qin Shi Huang", "259-210 BC", "first emperor of China", "He unified China in 221 BC, standardized writing, weights and money, and began early versions of the Great Wall. He was buried with the Terracotta Army."],
  "joan of arc": ["Joan of Arc", "c. 1412-1431", "French heroine and saint", "A peasant girl who said she was guided by divine voices, she helped lift the Siege of Orleans in 1429 during the Hundred Years' War. She was burned at the stake in 1431 and made a saint in 1920."],
  "adolf hitler": ["Adolf Hitler", "1889-1945", "dictator of Nazi Germany", "He led Germany from 1933 to 1945, started World War II in Europe by invading Poland in 1939, and was responsible for the Holocaust, the murder of six million Jews and millions of others."],
  "joseph stalin": ["Joseph Stalin", "1878-1953", "leader of the Soviet Union", "He ruled the Soviet Union from the late 1920s until his death in 1953, forcing rapid industrialization and collectivization, and his purges and famines killed millions. The USSR under him helped defeat Nazi Germany."],
  "mao zedong": ["Mao Zedong", "1893-1976", "founder of the People's Republic of China", "He led the Chinese Communist Party to victory and proclaimed the People's Republic in 1949. His Great Leap Forward and Cultural Revolution caused enormous loss of life."],
  "vladimir lenin": ["Vladimir Lenin", "1870-1924", "Russian revolutionary and Soviet leader", "He led the Bolsheviks in the October Revolution of 1917 and founded the Soviet state."],
  "otto von bismarck": ["Otto von Bismarck", "1815-1898", "Prussian and German statesman", "He unified Germany in 1871 and served as its first chancellor, known for his realpolitik diplomacy and early social welfare programs."],
  "simon bolivar": ["Simon Bolivar", "1783-1830", "South American independence leader", "Known as El Libertador, he led the liberation of Venezuela, Colombia, Ecuador, Peru and Bolivia from Spanish rule. Bolivia is named after him."],
  "mikhail gorbachev": ["Mikhail Gorbachev", "1931-2022", "last leader of the Soviet Union", "His reforms of glasnost (openness) and perestroika (restructuring) helped end the Cold War, and he won the 1990 Nobel Peace Prize. The Soviet Union dissolved in 1991."],
  "margaret thatcher": ["Margaret Thatcher", "1925-2013", "British prime minister", "She was the United Kingdom's first female prime minister, serving from 1979 to 1990, and was nicknamed the Iron Lady."],

  // ---- Civil rights and humanitarian figures ----
  "martin luther king jr": ["Martin Luther King Jr.", "1929-1968", "American Baptist minister and civil rights leader", "He led the Montgomery bus boycott and the nonviolent civil rights movement, and gave the 'I Have a Dream' speech at the 1963 March on Washington. He won the 1964 Nobel Peace Prize and was assassinated in 1968."],
  "rosa parks": ["Rosa Parks", "1913-2005", "American civil rights activist", "Her refusal to give up her bus seat to a white passenger in Montgomery, Alabama, on December 1, 1955, sparked the Montgomery bus boycott."],
  "malcolm x": ["Malcolm X", "1925-1965", "American Muslim minister and human rights activist", "A prominent spokesman for the Nation of Islam and later an independent voice for Black empowerment, he was assassinated in 1965. His autobiography remains widely read."],
  "harriet tubman": ["Harriet Tubman", "c. 1822-1913", "American abolitionist", "After escaping slavery, she returned many times to lead enslaved people to freedom on the Underground Railroad, and served as a scout and spy for the Union Army."],
  "frederick douglass": ["Frederick Douglass", "1818-1895", "American abolitionist, writer and orator", "After escaping slavery in 1838, he became a leading voice against slavery, and his autobiography Narrative of the Life of Frederick Douglass (1845) was a best-seller."],
  "susan b anthony": ["Susan B. Anthony", "1820-1906", "American women's rights activist", "She was a leader of the women's suffrage movement; the 19th Amendment (1920), which gave US women the vote, was nicknamed the Susan B. Anthony Amendment."],
  "mother teresa": ["Mother Teresa", "1910-1997", "Catholic nun and missionary", "She founded the Missionaries of Charity in Kolkata (Calcutta) in 1950 to serve the poorest people. She won the 1979 Nobel Peace Prize and was made a saint in 2016."],
  "florence nightingale": ["Florence Nightingale", "1820-1910", "English nurse and statistician", "Known as the Lady with the Lamp for her work during the Crimean War, she founded modern nursing and used statistics to improve hospital sanitation."],
  "anne frank": ["Anne Frank", "1929-1945", "German-born Jewish diarist", "Her diary, written while hiding from the Nazis in Amsterdam from 1942 to 1944, became one of the best-known books about the Holocaust. She died in the Bergen-Belsen concentration camp."],
  "helen keller": ["Helen Keller", "1880-1968", "American author and activist", "Deaf and blind from early childhood, she learned to communicate with the help of her teacher Anne Sullivan, graduated from college, and became a famous writer and advocate for people with disabilities."],
  "malala yousafzai": ["Malala Yousafzai", "born 1997", "Pakistani activist for girls' education", "She survived being shot by the Taliban in 2012 for campaigning for girls' education. In 2014, at 17, she became the youngest Nobel Peace Prize laureate."],

  // ---- Artists ----
  "leonardo da vinci": ["Leonardo da Vinci", "1452-1519", "Italian Renaissance painter, scientist and inventor", "He painted the Mona Lisa and The Last Supper, and his notebooks are full of anatomical studies and designs for machines. He is the classic example of a Renaissance polymath."],
  "michelangelo": ["Michelangelo", "1475-1564", "Italian Renaissance sculptor, painter and architect", "He sculpted David and the Pieta, painted the ceiling of the Sistine Chapel (1508-1512), and designed the dome of St. Peter's Basilica."],
  "vincent van gogh": ["Vincent van Gogh", "1853-1890", "Dutch Post-Impressionist painter", "Known for bold color and expressive brushwork in works like The Starry Night (1889) and his Sunflowers series, he achieved little success during his life but became one of the most famous artists in history."],
  "pablo picasso": ["Pablo Picasso", "1881-1973", "Spanish painter and sculptor", "He co-founded Cubism with Georges Braque and was one of the most influential artists of the 20th century. His works include Les Demoiselles d'Avignon and Guernica (1937)."],
  "claude monet": ["Claude Monet", "1840-1926", "French painter", "A founder of Impressionism, his painting Impression, Sunrise gave the movement its name. He is famous for his series of Water Lilies paintings."],
  "rembrandt": ["Rembrandt van Rijn", "1606-1669", "Dutch Golden Age painter", "A master of light and shadow, he is known for The Night Watch (1642) and for dozens of self-portraits."],
  "frida kahlo": ["Frida Kahlo", "1907-1954", "Mexican painter", "She is known for vivid self-portraits that explore identity, pain and Mexican culture."],
  "salvador dali": ["Salvador Dali", "1904-1989", "Spanish Surrealist painter", "He is famous for dreamlike images such as The Persistence of Memory (1931), with its melting clocks."],
  "raphael": ["Raphael", "1483-1520", "Italian Renaissance painter and architect", "With Leonardo and Michelangelo he is one of the great masters of the High Renaissance; his best-known work is The School of Athens in the Vatican."],
  "andy warhol": ["Andy Warhol", "1928-1987", "American artist", "A leading figure of pop art, he is known for his Campbell's Soup Cans and silkscreen portraits of celebrities such as Marilyn Monroe."],
  "walt disney": ["Walt Disney", "1901-1966", "American animator and entertainment pioneer", "He co-created Mickey Mouse (1928), produced Snow White and the Seven Dwarfs (1937), the first full-length cel-animated feature film, and opened Disneyland in 1955."],

  // ---- Writers ----
  "william shakespeare": ["William Shakespeare", "1564-1616", "English playwright and poet", "Widely regarded as the greatest writer in the English language, he wrote about 39 plays, including Hamlet, Romeo and Juliet and Macbeth, and 154 sonnets."],
  "charles dickens": ["Charles Dickens", "1812-1870", "English novelist", "He wrote Oliver Twist, A Christmas Carol (1843), David Copperfield and Great Expectations, often highlighting poverty and social injustice in Victorian England."],
  "jane austen": ["Jane Austen", "1775-1817", "English novelist", "Her witty novels about love, class and marriage include Pride and Prejudice (1813), Sense and Sensibility and Emma."],
  "mark twain": ["Mark Twain", "1835-1910", "American writer and humorist", "Born Samuel Clemens, he wrote The Adventures of Tom Sawyer and Adventures of Huckleberry Finn, often called the Great American Novel."],
  "leo tolstoy": ["Leo Tolstoy", "1828-1910", "Russian novelist", "He wrote War and Peace and Anna Karenina, considered among the greatest novels ever written."],
  "homer": ["Homer", "c. 8th century BC", "ancient Greek poet", "He is traditionally credited with the epic poems the Iliad and the Odyssey, foundational works of Western literature. Little is known for certain about his life."],
  "dante alighieri": ["Dante Alighieri", "c. 1265-1321", "Italian poet", "His Divine Comedy, a journey through Hell, Purgatory and Paradise, is a masterpiece of world literature and helped establish Italian as a literary language."],
  "george orwell": ["George Orwell", "1903-1950", "English novelist and essayist", "Born Eric Blair, he wrote Animal Farm (1945) and Nineteen Eighty-Four (1949), warnings about totalitarianism that gave us terms like Big Brother."],
  "ernest hemingway": ["Ernest Hemingway", "1899-1961", "American novelist and short-story writer", "Known for a spare, direct style, he wrote The Sun Also Rises, A Farewell to Arms and The Old Man and the Sea, and won the 1954 Nobel Prize in Literature."],
  "j k rowling": ["J. K. Rowling", "born 1965", "British author", "She wrote the Harry Potter series, beginning with Harry Potter and the Philosopher's Stone (1997), one of the best-selling book series in history."],
  "agatha christie": ["Agatha Christie", "1890-1976", "English crime novelist", "She created the detectives Hercule Poirot and Miss Marple and is one of the best-selling novelists of all time. Her play The Mousetrap is the longest-running play in history."],
  "edgar allan poe": ["Edgar Allan Poe", "1809-1849", "American writer and poet", "Known for dark, macabre tales and the poem The Raven (1845), he is also credited with inventing the modern detective story."],
  "fyodor dostoevsky": ["Fyodor Dostoevsky", "1821-1881", "Russian novelist", "He wrote Crime and Punishment and The Brothers Karamazov, novels that explore psychology, morality and faith."],
  "rabindranath tagore": ["Rabindranath Tagore", "1861-1941", "Bengali poet, writer and composer", "In 1913 he became the first non-European to win the Nobel Prize in Literature, largely for Gitanjali. He wrote the national anthems of India and Bangladesh."],
  "miguel de cervantes": ["Miguel de Cervantes", "1547-1616", "Spanish novelist", "His Don Quixote (published in two parts, 1605 and 1615) is often called the first modern novel."],
  "j r r tolkien": ["J. R. R. Tolkien", "1892-1973", "English writer and philologist", "He wrote The Hobbit (1937) and The Lord of the Rings (1954-1955), founding works of modern fantasy."],
  "victor hugo": ["Victor Hugo", "1802-1885", "French novelist and poet", "He wrote Les Miserables (1862) and The Hunchback of Notre-Dame (1831)."],
  "oscar wilde": ["Oscar Wilde", "1854-1900", "Irish writer and playwright", "Famous for his wit, he wrote the novel The Picture of Dorian Gray and the comedy The Importance of Being Earnest."],
  "franz kafka": ["Franz Kafka", "1883-1924", "Bohemian German-language writer", "His stories and novels, such as The Metamorphosis and The Trial, depict surreal, nightmarish situations, giving rise to the word Kafkaesque."],
  "maya angelou": ["Maya Angelou", "1928-2014", "American poet, memoirist and civil rights activist", "Her autobiography I Know Why the Caged Bird Sings (1969) became a classic of American literature."],
  "toni morrison": ["Toni Morrison", "1931-2019", "American novelist", "Her novels about Black American life include Beloved (1987), which won the Pulitzer Prize. She won the 1993 Nobel Prize in Literature."],
  "emily dickinson": ["Emily Dickinson", "1830-1886", "American poet", "She wrote nearly 1,800 poems, very few of which were published during her lifetime, and is now considered one of America's greatest poets."],
  "geoffrey chaucer": ["Geoffrey Chaucer", "c. 1343-1400", "English poet", "Called the father of English literature, he wrote The Canterbury Tales."],

  // ---- Composers and musicians ----
  "wolfgang amadeus mozart": ["Wolfgang Amadeus Mozart", "1756-1791", "Austrian composer", "A child prodigy from Salzburg, he composed over 600 works, including the operas The Marriage of Figaro, Don Giovanni and The Magic Flute, before dying at 35."],
  "ludwig van beethoven": ["Ludwig van Beethoven", "1770-1827", "German composer and pianist", "He bridged the Classical and Romantic eras and wrote nine symphonies, including the Ninth with its 'Ode to Joy'. He kept composing after becoming almost completely deaf."],
  "johann sebastian bach": ["Johann Sebastian Bach", "1685-1750", "German Baroque composer", "His works include the Brandenburg Concertos, the Mass in B minor and The Well-Tempered Clavier, and he is considered one of the greatest composers of all time."],
  "frederic chopin": ["Frederic Chopin", "1810-1849", "Polish composer and pianist", "He wrote mainly for solo piano, including nocturnes, etudes, mazurkas and polonaises, and is a central figure of the Romantic era."],
  "pyotr ilyich tchaikovsky": ["Pyotr Ilyich Tchaikovsky", "1840-1893", "Russian composer", "He wrote the ballets Swan Lake, The Sleeping Beauty and The Nutcracker, and the 1812 Overture."],
  "antonio vivaldi": ["Antonio Vivaldi", "1678-1741", "Italian Baroque composer and violinist", "He is best known for The Four Seasons, a set of four violin concertos."],
  "george frideric handel": ["George Frideric Handel", "1685-1759", "German-born British Baroque composer", "He is best known for the oratorio Messiah (1742), with its Hallelujah chorus, and for Water Music."],
  "joseph haydn": ["Joseph Haydn", "1732-1809", "Austrian Classical composer", "Called the father of the symphony and the string quartet, he wrote over 100 symphonies."],
  "richard wagner": ["Richard Wagner", "1813-1883", "German composer", "He is known for his operas, especially the four-opera cycle The Ring of the Nibelung."],
  "elvis presley": ["Elvis Presley", "1935-1977", "American singer and actor", "Known as the King of Rock and Roll, he was one of the most popular and influential musicians of the 20th century."],
  "john lennon": ["John Lennon", "1940-1980", "English singer-songwriter", "He co-founded the Beatles and co-wrote many of their songs with Paul McCartney, and later wrote Imagine. He was shot and killed in New York City in 1980."],
  "michael jackson": ["Michael Jackson", "1958-2009", "American singer and dancer", "Known as the King of Pop, his album Thriller (1982) is the best-selling album of all time."],
  "bob marley": ["Bob Marley", "1945-1981", "Jamaican singer-songwriter", "He brought reggae music to worldwide audiences with songs such as No Woman, No Cry and One Love."],
  "freddie mercury": ["Freddie Mercury", "1946-1991", "British singer and songwriter", "The lead vocalist of Queen, he wrote Bohemian Rhapsody and is considered one of the greatest rock singers."],
  "louis armstrong": ["Louis Armstrong", "1901-1971", "American jazz trumpeter and singer", "One of the most influential figures in jazz, he is known for his trumpet playing, gravelly voice and What a Wonderful World."],
  "bob dylan": ["Bob Dylan", "born 1941", "American singer-songwriter", "Known for songs such as Blowin' in the Wind and Like a Rolling Stone, he won the 2016 Nobel Prize in Literature."],

  // ---- Explorers and astronauts ----
  "christopher columbus": ["Christopher Columbus", "1451-1506", "Italian explorer sailing for Spain", "His 1492 voyage across the Atlantic reached the Caribbean and began lasting European contact with the Americas."],
  "marco polo": ["Marco Polo", "1254-1324", "Venetian merchant and traveler", "He traveled to China and spent years at the court of Kublai Khan; the book of his travels introduced Europeans to Asia."],
  "ferdinand magellan": ["Ferdinand Magellan", "c. 1480-1521", "Portuguese explorer sailing for Spain", "He led the expedition (1519-1522) that made the first circumnavigation of the Earth, though he was killed in the Philippines in 1521 and the voyage was completed under Juan Sebastian Elcano."],
  "vasco da gama": ["Vasco da Gama", "c. 1460-1524", "Portuguese explorer", "In 1498 he became the first European to reach India by sea, sailing around the Cape of Good Hope."],
  "neil armstrong": ["Neil Armstrong", "1930-2012", "American astronaut", "As commander of Apollo 11, he became the first person to walk on the Moon on July 20, 1969, saying 'That's one small step for man, one giant leap for mankind.'"],
  "buzz aldrin": ["Buzz Aldrin", "born 1930", "American astronaut", "As lunar module pilot of Apollo 11 in July 1969, he became the second person to walk on the Moon."],
  "yuri gagarin": ["Yuri Gagarin", "1934-1968", "Soviet cosmonaut", "On April 12, 1961, aboard Vostok 1, he became the first human to travel into space and orbit the Earth."],
  "amelia earhart": ["Amelia Earhart", "1897-1937", "American aviator", "In 1932 she became the first woman to fly solo across the Atlantic. She disappeared over the Pacific in 1937 while attempting to fly around the world."],
  "roald amundsen": ["Roald Amundsen", "1872-1928", "Norwegian polar explorer", "He led the first expedition to reach the South Pole, on December 14, 1911, and was the first to sail the Northwest Passage."],
  "edmund hillary": ["Edmund Hillary", "1919-2008", "New Zealand mountaineer", "With Tenzing Norgay, he made the first confirmed ascent of Mount Everest on May 29, 1953."],
  "tenzing norgay": ["Tenzing Norgay", "1914-1986", "Nepali-Indian Sherpa mountaineer", "With Edmund Hillary, he made the first confirmed ascent of Mount Everest on May 29, 1953."],
  "james cook": ["James Cook", "1728-1779", "British navigator and explorer", "He made three Pacific voyages, mapping New Zealand and the east coast of Australia (1770) and reaching Hawaii (1778), where he was killed in 1779."],
  "ibn battuta": ["Ibn Battuta", "1304-c. 1369", "Moroccan traveler and scholar", "Over about 30 years he traveled across Africa, the Middle East, Central and South Asia and China, recording his journeys in the Rihla."],

  // ---- Philosophers and thinkers ----
  "socrates": ["Socrates", "c. 470-399 BC", "ancient Greek philosopher", "A founder of Western philosophy, he taught through questioning (the Socratic method) and wrote nothing himself; we know him mainly through Plato. He was sentenced to death in Athens and drank hemlock."],
  "plato": ["Plato", "c. 428-348 BC", "ancient Greek philosopher", "A student of Socrates and teacher of Aristotle, he founded the Academy in Athens and wrote dialogues such as The Republic."],
  "aristotle": ["Aristotle", "384-322 BC", "ancient Greek philosopher and scientist", "A student of Plato and tutor of Alexander the Great, he wrote on logic, ethics, politics, biology and physics, and founded the Lyceum in Athens."],
  "confucius": ["Confucius", "551-479 BC", "Chinese philosopher and teacher", "His teachings on ethics, family loyalty and good government, collected in the Analects, shaped Chinese culture for over two thousand years."],
  "immanuel kant": ["Immanuel Kant", "1724-1804", "German philosopher", "A central figure of the Enlightenment, he wrote the Critique of Pure Reason (1781) and developed influential theories of knowledge and ethics."],
  "friedrich nietzsche": ["Friedrich Nietzsche", "1844-1900", "German philosopher", "He challenged traditional morality and religion, declared that 'God is dead', and wrote Thus Spoke Zarathustra."],
  "karl marx": ["Karl Marx", "1818-1883", "German philosopher and economist", "With Friedrich Engels he wrote The Communist Manifesto (1848), and he wrote Das Kapital. His ideas became the basis of communism."],
  "rene descartes": ["Rene Descartes", "1596-1650", "French philosopher and mathematician", "Called the father of modern philosophy, he wrote 'I think, therefore I am' and invented the Cartesian coordinate system."],
  "john locke": ["John Locke", "1632-1704", "English philosopher", "His ideas on natural rights to life, liberty and property, and government by consent, strongly influenced the American Declaration of Independence."],
  "adam smith": ["Adam Smith", "1723-1790", "Scottish economist and philosopher", "His book The Wealth of Nations (1776) laid the foundations of modern economics and described the 'invisible hand' of the market."],
  "sun tzu": ["Sun Tzu", "c. 6th-5th century BC", "ancient Chinese military strategist", "He is traditionally credited as the author of The Art of War, a classic text on strategy still studied today."],
  "niccolo machiavelli": ["Niccolo Machiavelli", "1469-1527", "Italian diplomat and political philosopher", "His book The Prince describes how rulers gain and keep power, giving rise to the word Machiavellian."],

  // ---- Religious founders and figures ----
  "jesus": ["Jesus of Nazareth", "c. 4 BC-c. AD 30", "Jewish preacher and central figure of Christianity", "Christians believe he is the Son of God and the Messiah. His teachings, crucifixion and reported resurrection are the foundation of Christianity."],
  "muhammad": ["Muhammad", "c. 570-632", "prophet and founder of Islam", "Muslims believe he received the revelations of the Quran from God. His migration from Mecca to Medina in 622 (the Hijra) marks the start of the Islamic calendar."],
  "gautama buddha": ["Siddhartha Gautama (the Buddha)", "c. 5th century BC", "spiritual teacher and founder of Buddhism", "A prince from the Himalayan foothills who gave up his royal life, he is said to have attained enlightenment at Bodh Gaya and taught the Four Noble Truths and the Eightfold Path."],
  "guru nanak": ["Guru Nanak", "1469-1539", "founder of Sikhism", "He was the first of the ten Sikh Gurus, teaching devotion to one God, equality and honest living."],
  "martin luther": ["Martin Luther", "1483-1546", "German theologian and religious reformer", "His Ninety-five Theses (1517) criticizing the Catholic Church launched the Protestant Reformation. He also translated the Bible into German."],

  // ---- Sports ----
  "muhammad ali": ["Muhammad Ali", "1942-2016", "American boxer", "Known as The Greatest, he won Olympic gold in 1960 and was a three-time world heavyweight champion. He was also famous for refusing the Vietnam War draft."],
  "michael jordan": ["Michael Jordan", "born 1963", "American basketball player", "He won six NBA championships with the Chicago Bulls (1991-1993 and 1996-1998) and is widely regarded as one of the greatest basketball players ever."],
  "pele": ["Pele", "1940-2022", "Brazilian footballer", "He is the only player to win three FIFA World Cups (1958, 1962 and 1970) and is regarded as one of the greatest footballers of all time."],
  "babe ruth": ["Babe Ruth", "1895-1948", "American baseball player", "A legendary slugger for the New York Yankees, he hit 714 career home runs, a record that stood until 1974."],
  "jesse owens": ["Jesse Owens", "1913-1980", "American track and field athlete", "He won four gold medals at the 1936 Berlin Olympics, undermining Nazi claims of racial superiority."],
  "usain bolt": ["Usain Bolt", "born 1986", "Jamaican sprinter", "He set world records in the 100 m (9.58 seconds) and 200 m (19.19 seconds) in 2009 and won eight Olympic gold medals."],
  "serena williams": ["Serena Williams", "born 1981", "American tennis player", "She won 23 Grand Slam singles titles, the most in the Open Era, and is considered one of the greatest tennis players of all time."],
  "roger federer": ["Roger Federer", "born 1981", "Swiss tennis player", "He won 20 Grand Slam singles titles, including a record eight Wimbledon men's singles titles."],
  "lionel messi": ["Lionel Messi", "born 1987", "Argentine footballer", "Widely considered one of the greatest footballers ever, he has won a record eight Ballon d'Or awards (as of 2025) and captained Argentina to the 2022 World Cup title."],
  "cristiano ronaldo": ["Cristiano Ronaldo", "born 1985", "Portuguese footballer", "A five-time Ballon d'Or winner, he is the all-time top scorer in men's international football and in the UEFA Champions League."],
  "diego maradona": ["Diego Maradona", "1960-2020", "Argentine footballer", "He captained Argentina to the 1986 World Cup, scoring both the 'Hand of God' goal and the 'Goal of the Century' against England in the same match."],
  "sachin tendulkar": ["Sachin Tendulkar", "born 1973", "Indian cricketer", "He scored 100 international centuries and is the leading run-scorer in both Test and One Day International cricket."],
  "michael phelps": ["Michael Phelps", "born 1985", "American swimmer", "He is the most decorated Olympian in history, with 28 medals, 23 of them gold."],
  "jackie robinson": ["Jackie Robinson", "1919-1972", "American baseball player", "In 1947 he broke Major League Baseball's color line with the Brooklyn Dodgers. His number 42 is retired across all of MLB."],
  "wayne gretzky": ["Wayne Gretzky", "born 1961", "Canadian ice hockey player", "Known as The Great One, he holds many NHL records, including most career points."],
  "tiger woods": ["Tiger Woods", "born 1975", "American golfer", "He has won 15 major championships and 82 PGA Tour events, tied for the most ever."],
  "kobe bryant": ["Kobe Bryant", "1978-2020", "American basketball player", "He spent his entire 20-season career with the Los Angeles Lakers, winning five NBA championships. He died in a helicopter crash in January 2020."],
  "lebron james": ["LeBron James", "born 1984", "American basketball player", "He has won NBA championships with Miami, Cleveland and Los Angeles, and became the NBA's all-time leading scorer in 2023."],

  // ---- Technology and business ----
  "bill gates": ["Bill Gates", "born 1955", "American businessman and philanthropist", "He co-founded Microsoft with Paul Allen in 1975, which made Windows and Office dominant in personal computing. He later co-founded the Bill and Melinda Gates Foundation."],
  "steve jobs": ["Steve Jobs", "1955-2011", "American entrepreneur and co-founder of Apple", "He co-founded Apple in 1976 with Steve Wozniak and led the creation of the Macintosh, iPod, iPhone (2007) and iPad. He also led Pixar Animation Studios."],
  "steve wozniak": ["Steve Wozniak", "born 1950", "American engineer and co-founder of Apple", "He designed Apple's first computers, the Apple I and the hugely successful Apple II."],
  "mark zuckerberg": ["Mark Zuckerberg", "born 1984", "American entrepreneur", "He co-founded Facebook in 2004 while a student at Harvard; the company was renamed Meta in 2021."],
  "elon musk": ["Elon Musk", "born 1971", "South African-born entrepreneur", "He founded the rocket company SpaceX in 2002 and became the leading figure behind the electric carmaker Tesla. He earlier founded X.com, which merged into PayPal."],
  "jeff bezos": ["Jeff Bezos", "born 1964", "American entrepreneur", "He founded Amazon in 1994 as an online bookstore and built it into one of the world's largest companies. He also founded the space company Blue Origin."],
  "larry page": ["Larry Page", "born 1973", "American computer scientist and entrepreneur", "He co-founded Google with Sergey Brin in 1998 and co-created the PageRank algorithm."],
  "sergey brin": ["Sergey Brin", "born 1973", "Russian-born American computer scientist and entrepreneur", "He co-founded Google with Larry Page in 1998, growing it out of a Stanford research project."],
  "linus torvalds": ["Linus Torvalds", "born 1969", "Finnish-American software engineer", "He created the Linux kernel in 1991 and the Git version control system in 2005."]
};

export const PEOPLE_ALIAS = {
  "einstein": "albert einstein", "newton": "isaac newton", "sir isaac newton": "isaac newton",
  "darwin": "charles darwin", "curie": "marie curie", "madame curie": "marie curie", "marie sklodowska curie": "marie curie",
  "galileo": "galileo galilei", "edison": "thomas edison", "thomas alva edison": "thomas edison",
  "hawking": "stephen hawking", "copernicus": "nicolaus copernicus", "kepler": "johannes kepler",
  "faraday": "michael faraday", "pasteur": "louis pasteur", "mendel": "gregor mendel",
  "turing": "alan turing", "lovelace": "ada lovelace", "ada byron": "ada lovelace",
  "bohr": "niels bohr", "planck": "max planck", "feynman": "richard feynman",
  "mendeleev": "dmitri mendeleev", "mendeleyev": "dmitri mendeleev", "dmitri mendeleyev": "dmitri mendeleev",
  "sagan": "carl sagan", "oppenheimer": "j robert oppenheimer", "robert oppenheimer": "j robert oppenheimer",
  "fermi": "enrico fermi", "heisenberg": "werner heisenberg",
  "schrodinger": "erwin schrodinger", "schroedinger": "erwin schrodinger", "erwin schroedinger": "erwin schrodinger",
  "euler": "leonhard euler", "gauss": "carl friedrich gauss", "ramanujan": "srinivasa ramanujan",
  "leibniz": "gottfried wilhelm leibniz", "gottfried leibniz": "gottfried wilhelm leibniz",
  "lavoisier": "antoine lavoisier", "cv raman": "c v raman", "freud": "sigmund freud",
  "babbage": "charles babbage", "goodall": "jane goodall",
  "graham bell": "alexander graham bell",
  "orville wright": "wright brothers", "wilbur wright": "wright brothers", "the wright brothers": "wright brothers",
  "gutenberg": "johannes gutenberg", "marconi": "guglielmo marconi",
  "berners-lee": "tim berners-lee", "tim berners lee": "tim berners-lee", "timothy berners-lee": "tim berners-lee",
  "ben franklin": "benjamin franklin",
  "lincoln": "abraham lincoln", "abe lincoln": "abraham lincoln", "honest abe": "abraham lincoln",
  "jefferson": "thomas jefferson", "napoleon": "napoleon bonaparte", "caesar": "julius caesar",
  "cleopatra vii": "cleopatra", "churchill": "winston churchill",
  "fdr": "franklin d roosevelt", "franklin roosevelt": "franklin d roosevelt", "franklin delano roosevelt": "franklin d roosevelt",
  "teddy roosevelt": "theodore roosevelt",
  "jfk": "john f kennedy", "john kennedy": "john f kennedy", "john fitzgerald kennedy": "john f kennedy",
  "reagan": "ronald reagan", "obama": "barack obama",
  "queen elizabeth i": "elizabeth i", "queen elizabeth ii": "elizabeth ii",
  "chinggis khan": "genghis khan", "mandela": "nelson mandela",
  "gandhi": "mahatma gandhi", "ghandi": "mahatma gandhi", "mohandas gandhi": "mahatma gandhi", "mohandas karamchand gandhi": "mahatma gandhi",
  "nehru": "jawaharlal nehru", "ambedkar": "b r ambedkar", "br ambedkar": "b r ambedkar", "babasaheb ambedkar": "b r ambedkar",
  "sardar patel": "vallabhbhai patel", "sardar vallabhbhai patel": "vallabhbhai patel",
  "abdul kalam": "apj abdul kalam", "a p j abdul kalam": "apj abdul kalam", "kalam": "apj abdul kalam",
  "vivekananda": "swami vivekananda", "shivaji maharaj": "shivaji", "chhatrapati shivaji": "shivaji",
  "ashoka the great": "ashoka", "asoka": "ashoka", "akbar the great": "akbar",
  "louis 14": "louis xiv", "sun king": "louis xiv",
  "ramesses ii": "ramses ii", "ramses the great": "ramses ii", "ramesses the great": "ramses ii",
  "king tut": "tutankhamun", "tutankhamen": "tutankhamun",
  "qin shi huangdi": "qin shi huang",
  "hitler": "adolf hitler", "stalin": "joseph stalin", "mao": "mao zedong", "mao tse-tung": "mao zedong", "chairman mao": "mao zedong",
  "lenin": "vladimir lenin", "bismarck": "otto von bismarck", "bolivar": "simon bolivar",
  "gorbachev": "mikhail gorbachev", "thatcher": "margaret thatcher",
  "mlk": "martin luther king jr", "martin luther king": "martin luther king jr", "dr martin luther king": "martin luther king jr", "mlk jr": "martin luther king jr",
  "tubman": "harriet tubman", "douglass": "frederick douglass",
  "susan anthony": "susan b anthony", "nightingale": "florence nightingale",
  "malala": "malala yousafzai",
  "da vinci": "leonardo da vinci", "leonardo": "leonardo da vinci",
  "van gogh": "vincent van gogh", "picasso": "pablo picasso", "monet": "claude monet",
  "rembrandt van rijn": "rembrandt", "frida": "frida kahlo", "dali": "salvador dali", "warhol": "andy warhol",
  "michelangelo buonarroti": "michelangelo",
  "shakespeare": "william shakespeare", "shakespear": "william shakespeare",
  "dickens": "charles dickens", "austen": "jane austen", "twain": "mark twain", "samuel clemens": "mark twain",
  "tolstoy": "leo tolstoy", "dante": "dante alighieri", "orwell": "george orwell", "eric blair": "george orwell",
  "hemingway": "ernest hemingway", "jk rowling": "j k rowling", "rowling": "j k rowling",
  "poe": "edgar allan poe", "dostoevsky": "fyodor dostoevsky", "dostoyevsky": "fyodor dostoevsky", "fyodor dostoyevsky": "fyodor dostoevsky",
  "tagore": "rabindranath tagore", "cervantes": "miguel de cervantes",
  "tolkien": "j r r tolkien", "jrr tolkien": "j r r tolkien",
  "kafka": "franz kafka", "chaucer": "geoffrey chaucer",
  "mozart": "wolfgang amadeus mozart", "beethoven": "ludwig van beethoven", "bach": "johann sebastian bach",
  "chopin": "frederic chopin", "tchaikovsky": "pyotr ilyich tchaikovsky", "vivaldi": "antonio vivaldi",
  "handel": "george frideric handel", "haydn": "joseph haydn", "wagner": "richard wagner",
  "elvis": "elvis presley", "lennon": "john lennon",
  "columbus": "christopher columbus", "magellan": "ferdinand magellan",
  "gagarin": "yuri gagarin", "earhart": "amelia earhart", "amundsen": "roald amundsen",
  "tenzing": "tenzing norgay", "captain cook": "james cook",
  "kant": "immanuel kant", "nietzsche": "friedrich nietzsche", "marx": "karl marx",
  "descartes": "rene descartes", "machiavelli": "niccolo machiavelli",
  "jesus christ": "jesus", "jesus of nazareth": "jesus",
  "prophet muhammad": "muhammad", "mohammed": "muhammad", "prophet mohammed": "muhammad",
  "buddha": "gautama buddha", "the buddha": "gautama buddha", "siddhartha gautama": "gautama buddha",
  "messi": "lionel messi", "cr7": "cristiano ronaldo", "maradona": "diego maradona",
  "sachin": "sachin tendulkar", "tendulkar": "sachin tendulkar",
  "federer": "roger federer", "phelps": "michael phelps", "gretzky": "wayne gretzky",
  "lebron": "lebron james", "kobe": "kobe bryant", "cassius clay": "muhammad ali",
  "zuckerberg": "mark zuckerberg", "bezos": "jeff bezos", "musk": "elon musk",
  "wozniak": "steve wozniak", "torvalds": "linus torvalds"
};

// ---------------------------------------------------------------------------
// ANIMALS: every field is a string or null (null = not confidently known, do not state).
// ---------------------------------------------------------------------------
export const ANIMALS = {
  "cat": { name: "cat", plural: "cats", life: "12 to 18 years (indoor cats often live longer)", diet: "carnivore: meat, in the wild mostly small mammals and birds", group: "mammal", speed: "up to about 48 km/h (30 mph)", fact: "Cats spend around 12 to 16 hours a day sleeping." },
  "dog": { name: "dog", plural: "dogs", life: "10 to 13 years on average (small breeds often live longer than large breeds)", diet: "omnivore: meat plus grains and vegetables; pet dogs mostly eat prepared dog food", group: "mammal", speed: "most dogs run about 25 to 30 km/h; greyhounds reach about 70 km/h (43 mph)", fact: "Dogs were the first animals domesticated by humans, descending from an ancient population of wolves more than 15,000 years ago." },
  "horse": { name: "horse", plural: "horses", life: "25 to 30 years", diet: "herbivore: grass, hay and grains", group: "mammal", speed: "gallops at about 40 to 48 km/h (25 to 30 mph); racehorses exceed 70 km/h (43 mph) in sprints", fact: "Horses can doze standing up thanks to a locking mechanism in their legs called the stay apparatus." },
  "cow": { name: "cow", plural: "cows", life: "can live about 20 years, though farmed cattle are usually kept for a much shorter time", diet: "herbivore: grass, hay and silage", group: "mammal", speed: null, fact: "Cows are ruminants with a four-compartment stomach, and they chew cud to break down tough plant material." },
  "pig": { name: "pig", plural: "pigs", life: "15 to 20 years", diet: "omnivore: roots, plants, grains, insects and small animals", group: "mammal", speed: null, fact: "Pigs are among the most intelligent domestic animals; they can barely sweat, so they wallow in mud to cool down." },
  "sheep": { name: "sheep", plural: "sheep", life: "10 to 12 years", diet: "herbivore: grass and other low plants", group: "mammal", speed: null, fact: "The wool of most domestic sheep keeps growing, so they need shearing at least once a year." },
  "goat": { name: "goat", plural: "goats", life: "15 to 18 years", diet: "herbivore: mostly leaves, shrubs and twigs, plus grass", group: "mammal", speed: null, fact: "Goats were among the first animals to be domesticated, roughly 10,000 years ago." },
  "chicken": { name: "chicken", plural: "chickens", life: "5 to 10 years", diet: "omnivore: seeds, grains, insects and worms", group: "bird", speed: null, fact: "Chickens are the most numerous bird on Earth, with a population in the tens of billions." },
  "duck": { name: "duck", plural: "ducks", life: "5 to 10 years", diet: "omnivore: aquatic plants, seeds, insects and small invertebrates", group: "bird", speed: null, fact: "Ducks keep their feathers waterproof by spreading oil from a preen gland near the tail." },
  "rabbit": { name: "rabbit", plural: "rabbits", life: "8 to 12 years as pets; often only 1 to 2 years in the wild", diet: "herbivore: grass, hay and leafy plants", group: "mammal", speed: null, fact: "A rabbit's teeth never stop growing, so it must keep chewing to wear them down." },
  "hamster": { name: "hamster", plural: "hamsters", life: "2 to 3 years", diet: "omnivore: seeds, grains, vegetables and insects", group: "mammal", speed: null, fact: "Hamsters carry food in stretchy cheek pouches that can extend back to their shoulders." },
  "guinea pig": { name: "guinea pig", plural: "guinea pigs", life: "5 to 7 years", diet: "herbivore: hay, grass and vegetables", group: "mammal", speed: null, fact: "Like humans, guinea pigs cannot make their own vitamin C and must get it from their food." },
  "mouse": { name: "mouse", plural: "mice", life: "usually under 1 year in the wild; about 2 years in captivity", diet: "omnivore: seeds, grains, fruit and insects", group: "mammal", speed: null, fact: "Mice are among the most widely used animals in scientific and medical research." },
  "rat": { name: "rat", plural: "rats", life: "about 1 year in the wild; 2 to 3 years in captivity", diet: "omnivore: grains, seeds, fruit, insects and scraps", group: "mammal", speed: null, fact: "Rats cannot vomit." },
  "lion": { name: "lion", plural: "lions", life: "10 to 14 years in the wild; up to about 20 in captivity", diet: "carnivore: large prey such as zebra, wildebeest and buffalo", group: "mammal", speed: "up to about 80 km/h (50 mph) in short bursts", fact: "Lions are the most social of the big cats, living in groups called prides." },
  "tiger": { name: "tiger", plural: "tigers", life: "10 to 15 years in the wild; up to about 20 in captivity", diet: "carnivore: deer, wild boar, buffalo and other large prey", group: "mammal", speed: "up to about 50 to 65 km/h (30 to 40 mph) in short bursts", fact: "The tiger is the largest living cat species, and each tiger's stripe pattern is unique." },
  "leopard": { name: "leopard", plural: "leopards", life: "12 to 17 years in the wild", diet: "carnivore: antelope, deer, monkeys and other prey", group: "mammal", speed: "up to about 58 km/h (36 mph)", fact: "Leopards often drag their kills up into trees to keep them away from lions and hyenas." },
  "cheetah": { name: "cheetah", plural: "cheetahs", life: "10 to 12 years in the wild", diet: "carnivore: gazelles, impala and other small antelope", group: "mammal", speed: "about 100 to 120 km/h (60 to 75 mph) in short sprints", fact: "The cheetah is the fastest land animal, and unlike lions and tigers it cannot roar; it chirps and purrs instead." },
  "jaguar": { name: "jaguar", plural: "jaguars", life: "12 to 15 years in the wild", diet: "carnivore: capybara, peccaries, caiman, turtles and fish", group: "mammal", speed: null, fact: "Jaguars have an exceptionally powerful bite and often kill prey by biting through the skull." },
  "wolf": { name: "wolf", plural: "wolves", life: "6 to 8 years in the wild; up to about 15 in captivity", diet: "carnivore: deer, elk, moose and smaller animals", group: "mammal", speed: "up to about 60 km/h (37 mph) in short bursts", fact: "Gray wolves live and hunt in family groups called packs." },
  "fox": { name: "fox", plural: "foxes", life: "2 to 5 years in the wild; longer in captivity", diet: "omnivore: rodents, rabbits, birds, insects and fruit", group: "mammal", speed: "up to about 50 km/h (31 mph)", fact: "The red fox has the widest natural range of any wild land carnivore." },
  "brown bear": { name: "brown bear", plural: "brown bears", life: "20 to 30 years in the wild", diet: "omnivore: berries, roots, grasses, insects, fish and mammals", group: "mammal", speed: "up to about 50 km/h (30 mph) in short bursts", fact: "Brown bears, including grizzlies, spend the winter in dens, living off fat reserves built up in autumn." },
  "polar bear": { name: "polar bear", plural: "polar bears", life: "15 to 25 years in the wild", diet: "carnivore: mainly seals", group: "mammal", speed: "about 40 km/h (25 mph) on land in short bursts", fact: "A polar bear's fur is not actually white; the hairs are translucent, and the skin underneath is black." },
  "giant panda": { name: "giant panda", plural: "giant pandas", life: "about 15 to 20 years in the wild; up to about 30 in captivity", diet: "herbivore: almost entirely bamboo (although it belongs to the order Carnivora)", group: "mammal", speed: null, fact: "Giant pandas spend 10 to 16 hours a day eating and can eat 12 to 38 kg of bamboo daily." },
  "elephant": { name: "elephant", plural: "elephants", life: "60 to 70 years", diet: "herbivore: grasses, leaves, bark, roots and fruit", group: "mammal", speed: "up to about 25 km/h (15 mph)", fact: "Elephants are the largest land animals, and their pregnancy lasts about 22 months, the longest of any land mammal." },
  "giraffe": { name: "giraffe", plural: "giraffes", life: "about 25 years in the wild", diet: "herbivore: leaves and shoots, especially from acacia trees", group: "mammal", speed: "up to about 60 km/h (37 mph)", fact: "Giraffes are the tallest animals, reaching about 5.5 m (18 ft), yet they have the same number of neck vertebrae as humans: seven." },
  "zebra": { name: "zebra", plural: "zebras", life: "about 20 to 25 years in the wild", diet: "herbivore: mainly grass", group: "mammal", speed: "up to about 65 km/h (40 mph)", fact: "Every zebra's stripe pattern is unique, like a fingerprint." },
  "hippopotamus": { name: "hippopotamus", plural: "hippopotamuses", life: "40 to 50 years", diet: "herbivore: mainly grass, grazed at night", group: "mammal", speed: "up to about 30 km/h (19 mph) on land", fact: "Hippos spend their days in water to stay cool and are considered one of the most dangerous large animals in Africa." },
  "rhinoceros": { name: "rhinoceros", plural: "rhinoceroses", life: "35 to 50 years", diet: "herbivore: grasses, leaves, shoots and fruit", group: "mammal", speed: "up to about 50 km/h (30 mph)", fact: "Rhino horns are made of keratin, the same protein found in human hair and fingernails." },
  "gorilla": { name: "gorilla", plural: "gorillas", life: "35 to 40 years in the wild; can exceed 50 in captivity", diet: "herbivore: mainly leaves, stems and fruit, with some insects", group: "mammal", speed: null, fact: "Gorillas are the largest living primates and share about 98 percent of their DNA with humans." },
  "chimpanzee": { name: "chimpanzee", plural: "chimpanzees", life: "30 to 40 years in the wild; can exceed 50 in captivity", diet: "omnivore: fruit, leaves, seeds, insects and sometimes meat", group: "mammal", speed: null, fact: "Chimpanzees and bonobos are humans' closest living relatives, and chimpanzees make and use tools." },
  "orangutan": { name: "orangutan", plural: "orangutans", life: "35 to 45 years in the wild", diet: "omnivore: mostly fruit, plus leaves, bark and insects", group: "mammal", speed: null, fact: "Orangutans are the largest tree-dwelling mammals and live in the wild only on Borneo and Sumatra." },
  "kangaroo": { name: "kangaroo", plural: "kangaroos", life: null, diet: "herbivore: grasses and other plants", group: "mammal", speed: "up to about 56 km/h (35 mph), faster in short bursts", fact: "Kangaroos are marsupials: their babies (joeys) are born tiny and finish developing in the mother's pouch." },
  "koala": { name: "koala", plural: "koalas", life: "about 10 to 15 years", diet: "herbivore: almost entirely eucalyptus leaves", group: "mammal", speed: null, fact: "Koalas are marsupials, not bears, and sleep up to 18 to 22 hours a day because their leaf diet provides little energy." },
  "camel": { name: "camel", plural: "camels", life: "40 to 50 years", diet: "herbivore: dry grasses, leaves and thorny desert plants", group: "mammal", speed: "up to about 65 km/h (40 mph) in short bursts", fact: "A camel's hump stores fat, not water; the fat can be used for energy when food is scarce." },
  "deer": { name: "deer", plural: "deer", life: null, diet: "herbivore: grass, leaves, twigs, acorns and fruit", group: "mammal", speed: null, fact: "Male deer grow and shed a new set of antlers every year; antlers are bone, unlike horns." },
  "moose": { name: "moose", plural: "moose", life: "15 to 25 years", diet: "herbivore: leaves, twigs, bark and aquatic plants", group: "mammal", speed: "up to about 56 km/h (35 mph)", fact: "The moose is the largest member of the deer family." },
  "bat": { name: "bat", plural: "bats", life: null, diet: "insectivore (most species): insects; other species eat fruit, nectar, small animals or blood", group: "mammal", speed: null, fact: "Bats are the only mammals capable of true powered flight, and many find prey in the dark by echolocation." },
  "squirrel": { name: "squirrel", plural: "squirrels", life: null, diet: "omnivore: mainly nuts, seeds, fruit and fungi, sometimes insects and eggs", group: "mammal", speed: null, fact: "Squirrels bury caches of nuts and do not recover all of them, which helps new trees grow." },
  "hedgehog": { name: "hedgehog", plural: "hedgehogs", life: "2 to 5 years", diet: "insectivore: insects, worms, snails and beetles", group: "mammal", speed: null, fact: "A hedgehog has around 5,000 to 7,000 spines and rolls into a ball to protect itself." },
  "sloth": { name: "sloth", plural: "sloths", life: null, diet: "herbivore: mainly leaves", group: "mammal", speed: "very slow: typically well under 1 km/h", fact: "Sloths are the slowest mammals, and three-toed sloths climb down from their trees only about once a week to defecate." },
  "dolphin": { name: "dolphin", plural: "dolphins", life: "about 40 to 60 years for bottlenose dolphins", diet: "carnivore: fish and squid", group: "mammal", speed: "about 30 to 35 km/h (19 to 22 mph) in bursts", fact: "Dolphins rest one half of the brain at a time, so they can keep surfacing to breathe while they sleep." },
  "blue whale": { name: "blue whale", plural: "blue whales", life: "about 80 to 90 years", diet: "filter feeder: almost entirely krill", group: "mammal", speed: "up to about 30 km/h (20 mph) in bursts", fact: "The blue whale is the largest animal known to have ever lived, reaching about 30 m (98 ft) and well over 150 tonnes." },
  "orca": { name: "orca", plural: "orcas", life: "about 30 to 50 years on average; some wild females exceed 80", diet: "carnivore: fish, seals, squid, seabirds and even other whales", group: "mammal", speed: "up to about 55 km/h (34 mph)", fact: "Despite the name killer whale, the orca is the largest member of the dolphin family." },
  "great white shark": { name: "great white shark", plural: "great white sharks", life: "70 years or more", diet: "carnivore: fish, seals, sea lions and dolphins", group: "fish", speed: null, fact: "Great white sharks can sense the tiny electric fields of prey using organs called ampullae of Lorenzini." },
  "octopus": { name: "octopus", plural: "octopuses", life: "1 to 2 years for most species", diet: "carnivore: crabs, shellfish and fish", group: "mollusk (cephalopod)", speed: null, fact: "An octopus has three hearts, blue blood and eight arms lined with suckers." },
  "jellyfish": { name: "jellyfish", plural: "jellyfish", life: null, diet: "carnivore: plankton, fish eggs and small fish", group: "cnidarian (invertebrate)", speed: null, fact: "Jellyfish have no brain, heart or bones, and their bodies are about 95 percent water." },
  "penguin": { name: "penguin", plural: "penguins", life: "about 15 to 20 years in the wild for many species", diet: "carnivore: fish, squid and krill", group: "bird", speed: "most swim about 6 to 12 km/h; gentoo penguins reach about 36 km/h (22 mph)", fact: "Penguins cannot fly, but their wings work as flippers, and almost all species live in the Southern Hemisphere." },
  "eagle": { name: "eagle", plural: "eagles", life: "about 20 to 30 years in the wild for large species such as bald and golden eagles", diet: "carnivore: fish, small mammals, birds and carrion", group: "bird", speed: "golden eagles can dive at over 240 km/h (150 mph)", fact: "Eagles have extremely sharp eyesight, estimated to be several times better than a human's." },
  "owl": { name: "owl", plural: "owls", life: null, diet: "carnivore: rodents and other small mammals, insects and birds", group: "bird", speed: null, fact: "Owls cannot move their eyes in their sockets, but they can turn their heads about 270 degrees." },
  "parrot": { name: "parrot", plural: "parrots", life: "varies by species; large parrots such as macaws and cockatoos can live 50 years or more", diet: "herbivore (mostly): seeds, nuts, fruit, buds and flowers", group: "bird", speed: null, fact: "Some parrots, notably African grey parrots, can learn to mimic hundreds of words." },
  "ostrich": { name: "ostrich", plural: "ostriches", life: "about 30 to 40 years, longer in captivity", diet: "omnivore: plants, seeds, roots, insects and small animals", group: "bird", speed: "up to about 70 km/h (43 mph)", fact: "The ostrich is the largest living bird and lays the largest eggs of any living bird; it cannot fly." },
  "flamingo": { name: "flamingo", plural: "flamingos", life: "20 to 30 years in the wild, often longer in captivity", diet: "filter feeder: algae, brine shrimp and other small invertebrates", group: "bird", speed: null, fact: "Flamingos get their pink color from carotenoid pigments in the algae and shrimp they eat." },
  "peregrine falcon": { name: "peregrine falcon", plural: "peregrine falcons", life: null, diet: "carnivore: mainly other birds caught in flight", group: "bird", speed: "over 320 km/h (200 mph) in a hunting dive", fact: "The peregrine falcon is the fastest animal on Earth and lives on every continent except Antarctica." },
  "hummingbird": { name: "hummingbird", plural: "hummingbirds", life: "3 to 5 years on average", diet: "nectarivore: flower nectar, plus small insects and spiders", group: "bird", speed: null, fact: "Hummingbirds can hover in place and are the only birds that can fly backwards." },
  "crocodile": { name: "crocodile", plural: "crocodiles", life: "often 50 years or more for large species", diet: "carnivore: fish, birds, reptiles and mammals", group: "reptile", speed: null, fact: "The saltwater crocodile is the largest living reptile, with large males reaching about 6 m (20 ft)." },
  "alligator": { name: "alligator", plural: "alligators", life: "about 35 to 50 years in the wild", diet: "carnivore: fish, turtles, birds and mammals", group: "reptile", speed: null, fact: "Alligators have a broad, U-shaped snout, while most crocodiles have a narrower, V-shaped one." },
  "snake": { name: "snake", plural: "snakes", life: null, diet: "carnivore: rodents, birds, eggs, fish, frogs and other animals, swallowed whole", group: "reptile", speed: null, fact: "Snakes smell with their forked tongues, which carry scent particles to the Jacobson's organ in the roof of the mouth." },
  "king cobra": { name: "king cobra", plural: "king cobras", life: null, diet: "carnivore: mainly other snakes", group: "reptile", speed: null, fact: "The king cobra is the world's longest venomous snake, reaching over 5 m (16 ft)." },
  "turtle": { name: "turtle", plural: "turtles", life: "varies by species; many live several decades", diet: "omnivore (most species): plants, insects, fish and jellyfish depending on species", group: "reptile", speed: null, fact: "A turtle's shell is part of its skeleton, fused to its ribs and spine, so it cannot leave its shell." },
  "tortoise": { name: "tortoise", plural: "tortoises", life: "often over 100 years for giant tortoises", diet: "herbivore: grasses, leaves, flowers and cacti", group: "reptile", speed: "giant tortoises move at about 0.3 km/h (0.2 mph)", fact: "Tortoises are land-dwelling turtles, and giant tortoises are among the longest-lived vertebrates." },
  "komodo dragon": { name: "Komodo dragon", plural: "Komodo dragons", life: "about 30 years in the wild", diet: "carnivore: deer, pigs, water buffalo and carrion", group: "reptile", speed: null, fact: "The Komodo dragon of Indonesia is the largest living lizard, reaching about 3 m (10 ft), and its bite delivers venom." },
  "frog": { name: "frog", plural: "frogs", life: null, diet: "carnivore (adults): insects, worms and spiders; tadpoles often eat algae", group: "amphibian", speed: null, fact: "Frogs can absorb water and some oxygen through their skin, which is why they need moist habitats." },
  "bee": { name: "honey bee", plural: "bees", life: "workers live about 5 to 6 weeks in summer; queens can live 2 to 5 years", diet: "herbivore: nectar and pollen", group: "insect", speed: "about 24 km/h (15 mph)", fact: "Honey bees tell each other where flowers are with a movement called the waggle dance." },
  "ant": { name: "ant", plural: "ants", life: "workers live weeks to a few years depending on species; some queens live over 20 years", diet: "omnivore: nectar, seeds, fungi, insects and other food depending on species", group: "insect", speed: null, fact: "Ants live in colonies with queens and workers, and many can carry objects several times their own weight." },
  "butterfly": { name: "butterfly", plural: "butterflies", life: "adults often live 2 to 4 weeks; migrating monarchs can live several months", diet: "herbivore: adults drink nectar; caterpillars eat leaves", group: "insect", speed: null, fact: "Butterflies taste with sensors on their feet." },
  "spider": { name: "spider", plural: "spiders", life: "1 to 2 years for many species; some tarantulas live 20 years or more", diet: "carnivore: mainly insects", group: "arachnid", speed: null, fact: "Spiders are arachnids, not insects: they have eight legs and two main body parts." },
  "mosquito": { name: "mosquito", plural: "mosquitoes", life: null, diet: "nectar feeder: both sexes drink plant juices; only females bite to take blood for their eggs", group: "insect", speed: null, fact: "By spreading diseases such as malaria, mosquitoes cause more human deaths than any other animal." },
  "goldfish": { name: "goldfish", plural: "goldfish", life: "10 to 15 years with good care; some exceed 20", diet: "omnivore: plants, algae, insects, small crustaceans and fish food", group: "fish", speed: null, fact: "Goldfish are domesticated carp first bred in China over 1,000 years ago, and the idea of a 3-second memory is a myth." },
  "seahorse": { name: "seahorse", plural: "seahorses", life: null, diet: "carnivore: tiny crustaceans and plankton", group: "fish", speed: null, fact: "In seahorses the male carries the eggs in a pouch and gives birth to the young." },
  "crow": { name: "crow", plural: "crows", life: null, diet: "omnivore: insects, seeds, fruit, small animals, eggs and carrion", group: "bird", speed: null, fact: "Crows are highly intelligent: some make and use tools, and they can recognize individual human faces." },
  "pigeon": { name: "pigeon", plural: "pigeons", life: "3 to 5 years in the wild; up to about 15 in captivity", diet: "herbivore: seeds and grains, plus scraps in cities", group: "bird", speed: null, fact: "Homing pigeons can find their way home from hundreds of kilometers away and carried messages in both World Wars." },
  "raccoon": { name: "raccoon", plural: "raccoons", life: "2 to 3 years in the wild; up to about 20 in captivity", diet: "omnivore: fruit, nuts, insects, frogs, eggs and scraps", group: "mammal", speed: null, fact: "Raccoons have very sensitive front paws and often dabble their food in water before eating." },
  "hyena": { name: "hyena", plural: "hyenas", life: null, diet: "carnivore: hunts antelope and zebra and also scavenges", group: "mammal", speed: null, fact: "Spotted hyenas are skilled hunters that kill most of their own food and live in clans led by females." },
  "sea otter": { name: "sea otter", plural: "sea otters", life: null, diet: "carnivore: sea urchins, crabs, clams and other shellfish", group: "mammal", speed: null, fact: "Sea otters have the densest fur of any animal and use rocks as tools to crack open shellfish." },
  "platypus": { name: "platypus", plural: "platypuses", life: null, diet: "carnivore: worms, insect larvae, shrimp and crayfish", group: "mammal (monotreme)", speed: null, fact: "The platypus is one of the few mammals that lay eggs, and males have venomous spurs on their hind legs." },
  "beaver": { name: "beaver", plural: "beavers", life: null, diet: "herbivore: bark, leaves, twigs and aquatic plants", group: "mammal", speed: null, fact: "Beavers build dams from branches and mud, creating ponds that change whole ecosystems; their teeth never stop growing." }
};

export const ANIMAL_ALIAS = {
  "cats": "cat", "kitten": "cat", "kittens": "cat", "kitty": "cat", "house cat": "cat", "domestic cat": "cat",
  "dogs": "dog", "puppy": "dog", "puppies": "dog", "doggy": "dog", "domestic dog": "dog",
  "horses": "horse", "pony": "horse", "ponies": "horse", "stallion": "horse", "mare": "horse",
  "cows": "cow", "cattle": "cow", "bull": "cow", "bulls": "cow", "ox": "cow", "oxen": "cow",
  "pigs": "pig", "piglet": "pig", "piglets": "pig", "hog": "pig", "hogs": "pig", "swine": "pig",
  "lamb": "sheep", "lambs": "sheep", "ewe": "sheep", "ram": "sheep",
  "goats": "goat",
  "chickens": "chicken", "hen": "chicken", "hens": "chicken", "rooster": "chicken", "roosters": "chicken", "chick": "chicken", "chicks": "chicken",
  "ducks": "duck", "duckling": "duck", "ducklings": "duck", "mallard": "duck",
  "rabbits": "rabbit", "bunny": "rabbit", "bunnies": "rabbit",
  "hamsters": "hamster", "guinea pigs": "guinea pig", "cavy": "guinea pig",
  "mice": "mouse", "house mouse": "mouse", "rats": "rat",
  "lions": "lion", "lioness": "lion", "tigers": "tiger", "tigress": "tiger", "bengal tiger": "tiger",
  "leopards": "leopard", "cheetahs": "cheetah", "jaguars": "jaguar",
  "wolves": "wolf", "gray wolf": "wolf", "grey wolf": "wolf",
  "foxes": "fox", "red fox": "fox",
  "brown bears": "brown bear", "bear": "brown bear", "bears": "brown bear", "grizzly": "brown bear", "grizzly bear": "brown bear", "grizzly bears": "brown bear",
  "polar bears": "polar bear",
  "giant pandas": "giant panda", "panda": "giant panda", "pandas": "giant panda", "panda bear": "giant panda",
  "elephants": "elephant", "african elephant": "elephant", "asian elephant": "elephant",
  "giraffes": "giraffe", "zebras": "zebra",
  "hippopotamuses": "hippopotamus", "hippopotami": "hippopotamus", "hippo": "hippopotamus", "hippos": "hippopotamus",
  "rhinoceroses": "rhinoceros", "rhino": "rhinoceros", "rhinos": "rhinoceros",
  "gorillas": "gorilla", "chimpanzees": "chimpanzee", "chimp": "chimpanzee", "chimps": "chimpanzee",
  "orangutans": "orangutan", "orangutang": "orangutan",
  "kangaroos": "kangaroo", "roo": "kangaroo", "koalas": "koala", "koala bear": "koala",
  "camels": "camel", "dromedary": "camel",
  "stag": "deer", "fawn": "deer", "moose": "moose",
  "bats": "bat", "squirrels": "squirrel", "hedgehogs": "hedgehog", "sloths": "sloth",
  "dolphins": "dolphin", "bottlenose dolphin": "dolphin",
  "blue whales": "blue whale", "whale": "blue whale", "whales": "blue whale",
  "orcas": "orca", "killer whale": "orca", "killer whales": "orca",
  "great white sharks": "great white shark", "great white": "great white shark", "shark": "great white shark", "sharks": "great white shark",
  "octopuses": "octopus", "octopi": "octopus",
  "jellyfishes": "jellyfish", "jelly fish": "jellyfish",
  "penguins": "penguin", "emperor penguin": "penguin",
  "eagles": "eagle", "bald eagle": "eagle", "golden eagle": "eagle",
  "owls": "owl", "parrots": "parrot", "ostriches": "ostrich", "flamingos": "flamingo", "flamingoes": "flamingo",
  "peregrine falcons": "peregrine falcon", "peregrine": "peregrine falcon", "falcon": "peregrine falcon", "falcons": "peregrine falcon",
  "hummingbirds": "hummingbird",
  "crocodiles": "crocodile", "croc": "crocodile", "saltwater crocodile": "crocodile",
  "alligators": "alligator", "gator": "alligator", "gators": "alligator",
  "snakes": "snake", "serpent": "snake",
  "king cobras": "king cobra", "cobra": "king cobra", "cobras": "king cobra",
  "turtles": "turtle", "sea turtle": "turtle", "tortoises": "tortoise", "giant tortoise": "tortoise",
  "komodo dragons": "komodo dragon", "komodo": "komodo dragon",
  "frogs": "frog",
  "bees": "bee", "honey bee": "bee", "honeybee": "bee", "honey bees": "bee", "honeybees": "bee",
  "ants": "ant", "butterflies": "butterfly", "spiders": "spider",
  "mosquitoes": "mosquito", "mosquitos": "mosquito",
  "goldfishes": "goldfish", "seahorses": "seahorse", "sea horse": "seahorse",
  "crows": "crow", "pigeons": "pigeon", "dove": "pigeon", "rock dove": "pigeon",
  "raccoons": "raccoon", "hyenas": "hyena", "spotted hyena": "hyena",
  "sea otters": "sea otter", "otter": "sea otter", "otters": "sea otter",
  "platypuses": "platypus", "beavers": "beaver"
};

// ---------------------------------------------------------------------------
// ANIMAL_RECORDS: superlatives, with the usual caveats spelled out.
// ---------------------------------------------------------------------------
export const ANIMAL_RECORDS = {
  "fastest animal": "The peregrine falcon is the fastest animal, reaching over 320 km/h (200 mph) in a hunting dive; the fastest land animal is the cheetah, at about 100 to 120 km/h (60 to 75 mph) in short sprints.",
  "fastest land animal": "The cheetah is the fastest land animal, reaching about 100 to 120 km/h (60 to 75 mph) in short sprints of a few hundred meters.",
  "largest animal": "The blue whale is the largest animal known to have ever lived, reaching about 30 m (98 ft) long and well over 150 tonnes.",
  "largest land animal": "The African bush elephant is the largest land animal; large males stand about 3 to 4 m (10 to 13 ft) at the shoulder and can weigh 6 tonnes or more.",
  "tallest animal": "The giraffe is the tallest animal, with adults reaching about 4.5 to 5.5 m (15 to 18 ft) and exceptional males nearly 6 m (19 ft).",
  "smallest mammal": "By weight, the Etruscan shrew is the smallest mammal, at about 2 grams; by body length, Kitti's hog-nosed bat (the bumblebee bat) is often named, at about 3 cm.",
  "longest living animal": "Among individual animals with verified ages, an ocean quahog clam nicknamed Ming lived about 507 years. The Greenland shark is the longest-lived known vertebrate, estimated to live about 250 to 500 years, and bowhead whales can live over 200 years.",
  "slowest animal": "The three-toed sloth is usually named the slowest mammal, moving well under 1 km/h. Animals such as garden snails, sea anemones and sea stars move even more slowly.",
  "largest bird": "The ostrich is the largest living bird, standing up to about 2.7 m (9 ft) tall and weighing over 100 kg. The bird with the largest wingspan is the wandering albatross, at up to about 3.5 m (11 ft).",
  "smallest bird": "The bee hummingbird of Cuba is the smallest bird, about 5 to 6 cm long and weighing around 2 grams.",
  "most venomous snake": "The inland taipan of Australia is considered the most venomous land snake, based on the toxicity of its venom in laboratory tests. It is shy and rarely bites people; snakes such as the saw-scaled viper and Russell's viper cause far more human deaths.",
  "largest fish": "The whale shark is the largest fish, commonly about 12 m (40 ft) long, with some reports approaching 18 m. It is a harmless filter feeder.",
  "loudest animal": "The sperm whale makes the loudest known sounds of any animal, with echolocation clicks reaching about 230 decibels underwater (underwater decibels are not directly comparable to sound in air). On land, howler monkeys are often cited as the loudest.",
  "strongest animal": "Relative to body size, a dung beetle species (Onthophagus taurus) is often named strongest, able to pull about 1,141 times its own body weight. In absolute terms, the African elephant is the strongest land animal.",
  "largest reptile": "The saltwater crocodile is the largest living reptile; large males reach about 6 m (20 ft) and can weigh over 1,000 kg.",
  "largest cat": "The tiger is the largest cat species; large males can weigh over 250 kg.",
  "longest snake": "The reticulated python is the longest snake, regularly exceeding 6 m (20 ft); the green anaconda is the heaviest snake.",
  "largest primate": "The gorilla is the largest living primate; adult male eastern gorillas can weigh around 200 kg.",
  "largest lizard": "The Komodo dragon of Indonesia is the largest living lizard, reaching about 3 m (10 ft) long."
};
